// WWNWatchKeymap.h — GENERATED, do not edit by hand.
// Complete, include-free US xkb keymap (XKB_KEYMAP_FORMAT_TEXT_V1),
// produced by `xkbcli compile-keymap --layout us` (libxkbcommon 1.13.2).
// Sent verbatim to weston-terminal via wl_keyboard.keymap so toytoolkit's
// xkbcommon can translate evdev keycodes -> UTF-8 on watchOS.
#pragma once

static const char kWWNWatchUSKeymap[] =
    "xkb_keymap {\n"
    "xkb_keycodes \"evdev_aliases(qwerty)\" {\n"
    "\tminimum = 8;\n"
    "\tmaximum = 709;\n"
    "\t<ESC>                = 9;\n"
    "\t<AE01>               = 10;\n"
    "\t<AE02>               = 11;\n"
    "\t<AE03>               = 12;\n"
    "\t<AE04>               = 13;\n"
    "\t<AE05>               = 14;\n"
    "\t<AE06>               = 15;\n"
    "\t<AE07>               = 16;\n"
    "\t<AE08>               = 17;\n"
    "\t<AE09>               = 18;\n"
    "\t<AE10>               = 19;\n"
    "\t<AE11>               = 20;\n"
    "\t<AE12>               = 21;\n"
    "\t<BKSP>               = 22;\n"
    "\t<TAB>                = 23;\n"
    "\t<AD01>               = 24;\n"
    "\t<AD02>               = 25;\n"
    "\t<AD03>               = 26;\n"
    "\t<AD04>               = 27;\n"
    "\t<AD05>               = 28;\n"
    "\t<AD06>               = 29;\n"
    "\t<AD07>               = 30;\n"
    "\t<AD08>               = 31;\n"
    "\t<AD09>               = 32;\n"
    "\t<AD10>               = 33;\n"
    "\t<AD11>               = 34;\n"
    "\t<AD12>               = 35;\n"
    "\t<RTRN>               = 36;\n"
    "\t<LCTL>               = 37;\n"
    "\t<AC01>               = 38;\n"
    "\t<AC02>               = 39;\n"
    "\t<AC03>               = 40;\n"
    "\t<AC04>               = 41;\n"
    "\t<AC05>               = 42;\n"
    "\t<AC06>               = 43;\n"
    "\t<AC07>               = 44;\n"
    "\t<AC08>               = 45;\n"
    "\t<AC09>               = 46;\n"
    "\t<AC10>               = 47;\n"
    "\t<AC11>               = 48;\n"
    "\t<TLDE>               = 49;\n"
    "\t<LFSH>               = 50;\n"
    "\t<BKSL>               = 51;\n"
    "\t<AB01>               = 52;\n"
    "\t<AB02>               = 53;\n"
    "\t<AB03>               = 54;\n"
    "\t<AB04>               = 55;\n"
    "\t<AB05>               = 56;\n"
    "\t<AB06>               = 57;\n"
    "\t<AB07>               = 58;\n"
    "\t<AB08>               = 59;\n"
    "\t<AB09>               = 60;\n"
    "\t<AB10>               = 61;\n"
    "\t<RTSH>               = 62;\n"
    "\t<KPMU>               = 63;\n"
    "\t<LALT>               = 64;\n"
    "\t<SPCE>               = 65;\n"
    "\t<CAPS>               = 66;\n"
    "\t<FK01>               = 67;\n"
    "\t<FK02>               = 68;\n"
    "\t<FK03>               = 69;\n"
    "\t<FK04>               = 70;\n"
    "\t<FK05>               = 71;\n"
    "\t<FK06>               = 72;\n"
    "\t<FK07>               = 73;\n"
    "\t<FK08>               = 74;\n"
    "\t<FK09>               = 75;\n"
    "\t<FK10>               = 76;\n"
    "\t<NMLK>               = 77;\n"
    "\t<SCLK>               = 78;\n"
    "\t<KP7>                = 79;\n"
    "\t<KP8>                = 80;\n"
    "\t<KP9>                = 81;\n"
    "\t<KPSU>               = 82;\n"
    "\t<KP4>                = 83;\n"
    "\t<KP5>                = 84;\n"
    "\t<KP6>                = 85;\n"
    "\t<KPAD>               = 86;\n"
    "\t<KP1>                = 87;\n"
    "\t<KP2>                = 88;\n"
    "\t<KP3>                = 89;\n"
    "\t<KP0>                = 90;\n"
    "\t<KPDL>               = 91;\n"
    "\t<LVL3>               = 92;\n"
    "\t<ZEHA>               = 93;\n"
    "\t<LSGT>               = 94;\n"
    "\t<FK11>               = 95;\n"
    "\t<FK12>               = 96;\n"
    "\t<AB11>               = 97;\n"
    "\t<KATA>               = 98;\n"
    "\t<HIRA>               = 99;\n"
    "\t<HENK>               = 100;\n"
    "\t<HKTG>               = 101;\n"
    "\t<MUHE>               = 102;\n"
    "\t<JPCM>               = 103;\n"
    "\t<KPEN>               = 104;\n"
    "\t<RCTL>               = 105;\n"
    "\t<KPDV>               = 106;\n"
    "\t<PRSC>               = 107;\n"
    "\t<RALT>               = 108;\n"
    "\t<LNFD>               = 109;\n"
    "\t<HOME>               = 110;\n"
    "\t<UP>                 = 111;\n"
    "\t<PGUP>               = 112;\n"
    "\t<LEFT>               = 113;\n"
    "\t<RGHT>               = 114;\n"
    "\t<END>                = 115;\n"
    "\t<DOWN>               = 116;\n"
    "\t<PGDN>               = 117;\n"
    "\t<INS>                = 118;\n"
    "\t<DELE>               = 119;\n"
    "\t<I120>               = 120;\n"
    "\t<MUTE>               = 121;\n"
    "\t<VOL->               = 122;\n"
    "\t<VOL+>               = 123;\n"
    "\t<POWR>               = 124;\n"
    "\t<KPEQ>               = 125;\n"
    "\t<I126>               = 126;\n"
    "\t<PAUS>               = 127;\n"
    "\t<I128>               = 128;\n"
    "\t<I129>               = 129;\n"
    "\t<HNGL>               = 130;\n"
    "\t<HJCV>               = 131;\n"
    "\t<AE13>               = 132;\n"
    "\t<LWIN>               = 133;\n"
    "\t<RWIN>               = 134;\n"
    "\t<COMP>               = 135;\n"
    "\t<STOP>               = 136;\n"
    "\t<AGAI>               = 137;\n"
    "\t<PROP>               = 138;\n"
    "\t<UNDO>               = 139;\n"
    "\t<FRNT>               = 140;\n"
    "\t<COPY>               = 141;\n"
    "\t<OPEN>               = 142;\n"
    "\t<PAST>               = 143;\n"
    "\t<FIND>               = 144;\n"
    "\t<CUT>                = 145;\n"
    "\t<HELP>               = 146;\n"
    "\t<I147>               = 147;\n"
    "\t<I148>               = 148;\n"
    "\t<I149>               = 149;\n"
    "\t<I150>               = 150;\n"
    "\t<I151>               = 151;\n"
    "\t<I152>               = 152;\n"
    "\t<I153>               = 153;\n"
    "\t<I154>               = 154;\n"
    "\t<I155>               = 155;\n"
    "\t<I156>               = 156;\n"
    "\t<I157>               = 157;\n"
    "\t<I158>               = 158;\n"
    "\t<I159>               = 159;\n"
    "\t<I160>               = 160;\n"
    "\t<I161>               = 161;\n"
    "\t<I162>               = 162;\n"
    "\t<I163>               = 163;\n"
    "\t<I164>               = 164;\n"
    "\t<I165>               = 165;\n"
    "\t<I166>               = 166;\n"
    "\t<I167>               = 167;\n"
    "\t<I168>               = 168;\n"
    "\t<I169>               = 169;\n"
    "\t<I170>               = 170;\n"
    "\t<I171>               = 171;\n"
    "\t<I172>               = 172;\n"
    "\t<I173>               = 173;\n"
    "\t<I174>               = 174;\n"
    "\t<I175>               = 175;\n"
    "\t<I176>               = 176;\n"
    "\t<I177>               = 177;\n"
    "\t<I178>               = 178;\n"
    "\t<I179>               = 179;\n"
    "\t<I180>               = 180;\n"
    "\t<I181>               = 181;\n"
    "\t<I182>               = 182;\n"
    "\t<I183>               = 183;\n"
    "\t<I184>               = 184;\n"
    "\t<I185>               = 185;\n"
    "\t<I186>               = 186;\n"
    "\t<I187>               = 187;\n"
    "\t<I188>               = 188;\n"
    "\t<I189>               = 189;\n"
    "\t<I190>               = 190;\n"
    "\t<FK13>               = 191;\n"
    "\t<FK14>               = 192;\n"
    "\t<FK15>               = 193;\n"
    "\t<FK16>               = 194;\n"
    "\t<FK17>               = 195;\n"
    "\t<FK18>               = 196;\n"
    "\t<FK19>               = 197;\n"
    "\t<FK20>               = 198;\n"
    "\t<FK21>               = 199;\n"
    "\t<FK22>               = 200;\n"
    "\t<FK23>               = 201;\n"
    "\t<FK24>               = 202;\n"
    "\t<LVL5>               = 203;\n"
    "\t<ALT>                = 204;\n"
    "\t<META>               = 205;\n"
    "\t<SUPR>               = 206;\n"
    "\t<HYPR>               = 207;\n"
    "\t<I208>               = 208;\n"
    "\t<I209>               = 209;\n"
    "\t<I210>               = 210;\n"
    "\t<I211>               = 211;\n"
    "\t<I212>               = 212;\n"
    "\t<I213>               = 213;\n"
    "\t<I214>               = 214;\n"
    "\t<I215>               = 215;\n"
    "\t<I216>               = 216;\n"
    "\t<I217>               = 217;\n"
    "\t<I218>               = 218;\n"
    "\t<I219>               = 219;\n"
    "\t<I220>               = 220;\n"
    "\t<I221>               = 221;\n"
    "\t<I222>               = 222;\n"
    "\t<I223>               = 223;\n"
    "\t<I224>               = 224;\n"
    "\t<I225>               = 225;\n"
    "\t<I226>               = 226;\n"
    "\t<I227>               = 227;\n"
    "\t<I228>               = 228;\n"
    "\t<I229>               = 229;\n"
    "\t<I230>               = 230;\n"
    "\t<I231>               = 231;\n"
    "\t<I232>               = 232;\n"
    "\t<I233>               = 233;\n"
    "\t<I234>               = 234;\n"
    "\t<I235>               = 235;\n"
    "\t<I236>               = 236;\n"
    "\t<I237>               = 237;\n"
    "\t<I238>               = 238;\n"
    "\t<I239>               = 239;\n"
    "\t<I240>               = 240;\n"
    "\t<I241>               = 241;\n"
    "\t<I242>               = 242;\n"
    "\t<I243>               = 243;\n"
    "\t<I244>               = 244;\n"
    "\t<I245>               = 245;\n"
    "\t<I246>               = 246;\n"
    "\t<I247>               = 247;\n"
    "\t<I248>               = 248;\n"
    "\t<I249>               = 249;\n"
    "\t<I250>               = 250;\n"
    "\t<I251>               = 251;\n"
    "\t<I252>               = 252;\n"
    "\t<I253>               = 253;\n"
    "\t<I254>               = 254;\n"
    "\t<I255>               = 255;\n"
    "\t<I256>               = 256;\n"
    "\t<I360>               = 360;\n"
    "\t<I361>               = 361;\n"
    "\t<I362>               = 362;\n"
    "\t<I363>               = 363;\n"
    "\t<I364>               = 364;\n"
    "\t<I365>               = 365;\n"
    "\t<I366>               = 366;\n"
    "\t<I367>               = 367;\n"
    "\t<I368>               = 368;\n"
    "\t<I369>               = 369;\n"
    "\t<I370>               = 370;\n"
    "\t<I371>               = 371;\n"
    "\t<I372>               = 372;\n"
    "\t<I373>               = 373;\n"
    "\t<I374>               = 374;\n"
    "\t<I375>               = 375;\n"
    "\t<I376>               = 376;\n"
    "\t<I377>               = 377;\n"
    "\t<I378>               = 378;\n"
    "\t<I379>               = 379;\n"
    "\t<I380>               = 380;\n"
    "\t<I381>               = 381;\n"
    "\t<I382>               = 382;\n"
    "\t<I383>               = 383;\n"
    "\t<I384>               = 384;\n"
    "\t<I385>               = 385;\n"
    "\t<I386>               = 386;\n"
    "\t<I387>               = 387;\n"
    "\t<I388>               = 388;\n"
    "\t<I389>               = 389;\n"
    "\t<I390>               = 390;\n"
    "\t<I391>               = 391;\n"
    "\t<I392>               = 392;\n"
    "\t<I393>               = 393;\n"
    "\t<I394>               = 394;\n"
    "\t<I395>               = 395;\n"
    "\t<I396>               = 396;\n"
    "\t<I397>               = 397;\n"
    "\t<I398>               = 398;\n"
    "\t<I399>               = 399;\n"
    "\t<I400>               = 400;\n"
    "\t<I401>               = 401;\n"
    "\t<I402>               = 402;\n"
    "\t<I403>               = 403;\n"
    "\t<I404>               = 404;\n"
    "\t<I405>               = 405;\n"
    "\t<I406>               = 406;\n"
    "\t<I407>               = 407;\n"
    "\t<I408>               = 408;\n"
    "\t<I409>               = 409;\n"
    "\t<I410>               = 410;\n"
    "\t<I411>               = 411;\n"
    "\t<I412>               = 412;\n"
    "\t<I413>               = 413;\n"
    "\t<I414>               = 414;\n"
    "\t<I415>               = 415;\n"
    "\t<I416>               = 416;\n"
    "\t<I417>               = 417;\n"
    "\t<I418>               = 418;\n"
    "\t<I419>               = 419;\n"
    "\t<I420>               = 420;\n"
    "\t<I421>               = 421;\n"
    "\t<I422>               = 422;\n"
    "\t<I423>               = 423;\n"
    "\t<I424>               = 424;\n"
    "\t<I425>               = 425;\n"
    "\t<I426>               = 426;\n"
    "\t<I427>               = 427;\n"
    "\t<I428>               = 428;\n"
    "\t<I429>               = 429;\n"
    "\t<I430>               = 430;\n"
    "\t<I431>               = 431;\n"
    "\t<I432>               = 432;\n"
    "\t<I433>               = 433;\n"
    "\t<I434>               = 434;\n"
    "\t<I435>               = 435;\n"
    "\t<I436>               = 436;\n"
    "\t<I437>               = 437;\n"
    "\t<I438>               = 438;\n"
    "\t<I439>               = 439;\n"
    "\t<I440>               = 440;\n"
    "\t<I441>               = 441;\n"
    "\t<I442>               = 442;\n"
    "\t<I443>               = 443;\n"
    "\t<I444>               = 444;\n"
    "\t<I445>               = 445;\n"
    "\t<I446>               = 446;\n"
    "\t<I447>               = 447;\n"
    "\t<I448>               = 448;\n"
    "\t<I449>               = 449;\n"
    "\t<I450>               = 450;\n"
    "\t<I452>               = 452;\n"
    "\t<I453>               = 453;\n"
    "\t<I454>               = 454;\n"
    "\t<I455>               = 455;\n"
    "\t<I456>               = 456;\n"
    "\t<I457>               = 457;\n"
    "\t<I458>               = 458;\n"
    "\t<I459>               = 459;\n"
    "\t<I472>               = 472;\n"
    "\t<I473>               = 473;\n"
    "\t<I474>               = 474;\n"
    "\t<I475>               = 475;\n"
    "\t<I476>               = 476;\n"
    "\t<I477>               = 477;\n"
    "\t<I478>               = 478;\n"
    "\t<I479>               = 479;\n"
    "\t<I480>               = 480;\n"
    "\t<I481>               = 481;\n"
    "\t<I482>               = 482;\n"
    "\t<I483>               = 483;\n"
    "\t<I484>               = 484;\n"
    "\t<I485>               = 485;\n"
    "\t<I486>               = 486;\n"
    "\t<I487>               = 487;\n"
    "\t<I488>               = 488;\n"
    "\t<I489>               = 489;\n"
    "\t<I490>               = 490;\n"
    "\t<I491>               = 491;\n"
    "\t<I492>               = 492;\n"
    "\t<I493>               = 493;\n"
    "\t<I505>               = 505;\n"
    "\t<I506>               = 506;\n"
    "\t<I507>               = 507;\n"
    "\t<I508>               = 508;\n"
    "\t<I509>               = 509;\n"
    "\t<I510>               = 510;\n"
    "\t<I511>               = 511;\n"
    "\t<I512>               = 512;\n"
    "\t<I513>               = 513;\n"
    "\t<I514>               = 514;\n"
    "\t<I520>               = 520;\n"
    "\t<I521>               = 521;\n"
    "\t<I522>               = 522;\n"
    "\t<I523>               = 523;\n"
    "\t<I524>               = 524;\n"
    "\t<I525>               = 525;\n"
    "\t<I526>               = 526;\n"
    "\t<I527>               = 527;\n"
    "\t<I528>               = 528;\n"
    "\t<I529>               = 529;\n"
    "\t<I530>               = 530;\n"
    "\t<I531>               = 531;\n"
    "\t<I532>               = 532;\n"
    "\t<I533>               = 533;\n"
    "\t<I534>               = 534;\n"
    "\t<I535>               = 535;\n"
    "\t<I536>               = 536;\n"
    "\t<I537>               = 537;\n"
    "\t<I538>               = 538;\n"
    "\t<I539>               = 539;\n"
    "\t<I540>               = 540;\n"
    "\t<I541>               = 541;\n"
    "\t<I542>               = 542;\n"
    "\t<I543>               = 543;\n"
    "\t<I544>               = 544;\n"
    "\t<I545>               = 545;\n"
    "\t<I546>               = 546;\n"
    "\t<I547>               = 547;\n"
    "\t<I548>               = 548;\n"
    "\t<I549>               = 549;\n"
    "\t<I550>               = 550;\n"
    "\t<I568>               = 568;\n"
    "\t<I569>               = 569;\n"
    "\t<I570>               = 570;\n"
    "\t<I584>               = 584;\n"
    "\t<I585>               = 585;\n"
    "\t<I586>               = 586;\n"
    "\t<I587>               = 587;\n"
    "\t<I588>               = 588;\n"
    "\t<I589>               = 589;\n"
    "\t<I590>               = 590;\n"
    "\t<I591>               = 591;\n"
    "\t<I592>               = 592;\n"
    "\t<I593>               = 593;\n"
    "\t<I594>               = 594;\n"
    "\t<I595>               = 595;\n"
    "\t<I596>               = 596;\n"
    "\t<I597>               = 597;\n"
    "\t<I598>               = 598;\n"
    "\t<I599>               = 599;\n"
    "\t<I600>               = 600;\n"
    "\t<I601>               = 601;\n"
    "\t<I602>               = 602;\n"
    "\t<I603>               = 603;\n"
    "\t<I604>               = 604;\n"
    "\t<I605>               = 605;\n"
    "\t<I606>               = 606;\n"
    "\t<I616>               = 616;\n"
    "\t<I617>               = 617;\n"
    "\t<I618>               = 618;\n"
    "\t<I619>               = 619;\n"
    "\t<I620>               = 620;\n"
    "\t<I621>               = 621;\n"
    "\t<I622>               = 622;\n"
    "\t<I623>               = 623;\n"
    "\t<I624>               = 624;\n"
    "\t<I625>               = 625;\n"
    "\t<I626>               = 626;\n"
    "\t<I627>               = 627;\n"
    "\t<I628>               = 628;\n"
    "\t<I629>               = 629;\n"
    "\t<I630>               = 630;\n"
    "\t<I631>               = 631;\n"
    "\t<I632>               = 632;\n"
    "\t<I633>               = 633;\n"
    "\t<I634>               = 634;\n"
    "\t<I635>               = 635;\n"
    "\t<I636>               = 636;\n"
    "\t<I637>               = 637;\n"
    "\t<I638>               = 638;\n"
    "\t<I639>               = 639;\n"
    "\t<I640>               = 640;\n"
    "\t<I641>               = 641;\n"
    "\t<I642>               = 642;\n"
    "\t<I643>               = 643;\n"
    "\t<I644>               = 644;\n"
    "\t<I645>               = 645;\n"
    "\t<I646>               = 646;\n"
    "\t<I647>               = 647;\n"
    "\t<I648>               = 648;\n"
    "\t<I649>               = 649;\n"
    "\t<I650>               = 650;\n"
    "\t<I651>               = 651;\n"
    "\t<I652>               = 652;\n"
    "\t<I653>               = 653;\n"
    "\t<I654>               = 654;\n"
    "\t<I655>               = 655;\n"
    "\t<I656>               = 656;\n"
    "\t<I657>               = 657;\n"
    "\t<I664>               = 664;\n"
    "\t<I665>               = 665;\n"
    "\t<I666>               = 666;\n"
    "\t<I667>               = 667;\n"
    "\t<I668>               = 668;\n"
    "\t<I669>               = 669;\n"
    "\t<I670>               = 670;\n"
    "\t<I671>               = 671;\n"
    "\t<I672>               = 672;\n"
    "\t<I673>               = 673;\n"
    "\t<I674>               = 674;\n"
    "\t<I675>               = 675;\n"
    "\t<I676>               = 676;\n"
    "\t<I677>               = 677;\n"
    "\t<I678>               = 678;\n"
    "\t<I679>               = 679;\n"
    "\t<I680>               = 680;\n"
    "\t<I681>               = 681;\n"
    "\t<I682>               = 682;\n"
    "\t<I683>               = 683;\n"
    "\t<I684>               = 684;\n"
    "\t<I685>               = 685;\n"
    "\t<I686>               = 686;\n"
    "\t<I687>               = 687;\n"
    "\t<I688>               = 688;\n"
    "\t<I689>               = 689;\n"
    "\t<I690>               = 690;\n"
    "\t<I691>               = 691;\n"
    "\t<I692>               = 692;\n"
    "\t<I693>               = 693;\n"
    "\t<I696>               = 696;\n"
    "\t<I697>               = 697;\n"
    "\t<I698>               = 698;\n"
    "\t<I699>               = 699;\n"
    "\t<I700>               = 700;\n"
    "\t<I701>               = 701;\n"
    "\t<I704>               = 704;\n"
    "\t<I705>               = 705;\n"
    "\t<I706>               = 706;\n"
    "\t<I707>               = 707;\n"
    "\t<I708>               = 708;\n"
    "\t<I709>               = 709;\n"
    "\tindicator 1 = \"Caps Lock\";\n"
    "\tindicator 2 = \"Num Lock\";\n"
    "\tindicator 3 = \"Scroll Lock\";\n"
    "\tindicator 4 = \"Compose\";\n"
    "\tindicator 5 = \"Kana\";\n"
    "\tindicator 6 = \"Sleep\";\n"
    "\tindicator 7 = \"Suspend\";\n"
    "\tindicator 8 = \"Mute\";\n"
    "\tindicator 9 = \"Misc\";\n"
    "\tindicator 10 = \"Mail\";\n"
    "\tindicator 11 = \"Charging\";\n"
    "\tindicator 12 = \"Shift Lock\";\n"
    "\tindicator 13 = \"Group 2\";\n"
    "\tindicator 14 = \"Mouse Keys\";\n"
    "\talias <AC12>         = <BKSL>;\n"
    "\talias <ALGR>         = <RALT>;\n"
    "\talias <MENU>         = <COMP>;\n"
    "\talias <HZTG>         = <TLDE>;\n"
    "\talias <LMTA>         = <LWIN>;\n"
    "\talias <RMTA>         = <RWIN>;\n"
    "\talias <OUTP>         = <I235>;\n"
    "\talias <KITG>         = <I236>;\n"
    "\talias <KIDN>         = <I237>;\n"
    "\talias <KIUP>         = <I238>;\n"
    "\talias <I121>         = <MUTE>;\n"
    "\talias <I122>         = <VOL->;\n"
    "\talias <I123>         = <VOL+>;\n"
    "\talias <I124>         = <POWR>;\n"
    "\talias <I125>         = <KPEQ>;\n"
    "\talias <I127>         = <PAUS>;\n"
    "\talias <I130>         = <HNGL>;\n"
    "\talias <I131>         = <HJCV>;\n"
    "\talias <I132>         = <AE13>;\n"
    "\talias <I133>         = <LWIN>;\n"
    "\talias <I134>         = <RWIN>;\n"
    "\talias <I135>         = <COMP>;\n"
    "\talias <I136>         = <STOP>;\n"
    "\talias <I137>         = <AGAI>;\n"
    "\talias <I138>         = <PROP>;\n"
    "\talias <I139>         = <UNDO>;\n"
    "\talias <I140>         = <FRNT>;\n"
    "\talias <I141>         = <COPY>;\n"
    "\talias <I142>         = <OPEN>;\n"
    "\talias <I143>         = <PAST>;\n"
    "\talias <I144>         = <FIND>;\n"
    "\talias <I145>         = <CUT>;\n"
    "\talias <I146>         = <HELP>;\n"
    "\talias <I191>         = <FK13>;\n"
    "\talias <I192>         = <FK14>;\n"
    "\talias <I193>         = <FK15>;\n"
    "\talias <I194>         = <FK16>;\n"
    "\talias <I195>         = <FK17>;\n"
    "\talias <I196>         = <FK18>;\n"
    "\talias <I197>         = <FK19>;\n"
    "\talias <I198>         = <FK20>;\n"
    "\talias <I199>         = <FK21>;\n"
    "\talias <I200>         = <FK22>;\n"
    "\talias <I201>         = <FK23>;\n"
    "\talias <I202>         = <FK24>;\n"
    "\talias <MDSW>         = <LVL5>;\n"
    "\talias <KPPT>         = <I129>;\n"
    "\talias <LatQ>         = <AD01>;\n"
    "\talias <LatW>         = <AD02>;\n"
    "\talias <LatE>         = <AD03>;\n"
    "\talias <LatR>         = <AD04>;\n"
    "\talias <LatT>         = <AD05>;\n"
    "\talias <LatY>         = <AD06>;\n"
    "\talias <LatU>         = <AD07>;\n"
    "\talias <LatI>         = <AD08>;\n"
    "\talias <LatO>         = <AD09>;\n"
    "\talias <LatP>         = <AD10>;\n"
    "\talias <LatA>         = <AC01>;\n"
    "\talias <LatS>         = <AC02>;\n"
    "\talias <LatD>         = <AC03>;\n"
    "\talias <LatF>         = <AC04>;\n"
    "\talias <LatG>         = <AC05>;\n"
    "\talias <LatH>         = <AC06>;\n"
    "\talias <LatJ>         = <AC07>;\n"
    "\talias <LatK>         = <AC08>;\n"
    "\talias <LatL>         = <AC09>;\n"
    "\talias <LatZ>         = <AB01>;\n"
    "\talias <LatX>         = <AB02>;\n"
    "\talias <LatC>         = <AB03>;\n"
    "\talias <LatV>         = <AB04>;\n"
    "\talias <LatB>         = <AB05>;\n"
    "\talias <LatN>         = <AB06>;\n"
    "\talias <LatM>         = <AB07>;\n"
    "};\n"
    "\n"
    "xkb_types \"complete\" {\n"
    "\tvirtual_modifiers NumLock,Alt,LevelThree,Super,LevelFive,Meta,Hyper=0x4000,ScrollLock=0x8000;\n"
    "\n"
    "\ttype \"ONE_LEVEL\" {\n"
    "\t\tmodifiers= none;\n"
    "\t\tlevel_name[1]= \"Any\";\n"
    "\t};\n"
    "\ttype \"TWO_LEVEL\" {\n"
    "\t\tmodifiers= Shift;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t};\n"
    "\ttype \"ALPHABETIC\" {\n"
    "\t\tmodifiers= Shift+Lock;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[Lock]= 2;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Caps\";\n"
    "\t};\n"
    "\ttype \"PC_ALT_LEVEL2\" {\n"
    "\t\tmodifiers= Alt;\n"
    "\t\tmap[Alt]= 2;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Alt\";\n"
    "\t};\n"
    "\ttype \"PC_SUPER_LEVEL2\" {\n"
    "\t\tmodifiers= Super;\n"
    "\t\tmap[Super]= 2;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Super\";\n"
    "\t};\n"
    "\ttype \"PC_SHIFT_SUPER_LEVEL2\" {\n"
    "\t\tmodifiers= Shift+Super;\n"
    "\t\tmap[Shift+Super]= 2;\n"
    "\t\tmap[Shift]= 1;\n"
    "\t\tpreserve[Shift]= Shift;\n"
    "\t\tmap[Super]= 1;\n"
    "\t\tpreserve[Super]= Super;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Super\";\n"
    "\t};\n"
    "\ttype \"PC_CONTROL_LEVEL2\" {\n"
    "\t\tmodifiers= Control;\n"
    "\t\tmap[Control]= 2;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Control\";\n"
    "\t};\n"
    "\ttype \"PC_CONTROL_SUPER_LEVEL2\" {\n"
    "\t\tmodifiers= Control+Super;\n"
    "\t\tmap[Control+Super]= 2;\n"
    "\t\tmap[Control]= 1;\n"
    "\t\tpreserve[Control]= Control;\n"
    "\t\tmap[Super]= 1;\n"
    "\t\tpreserve[Super]= Super;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Control + Super\";\n"
    "\t};\n"
    "\ttype \"CTRL+ALT\" {\n"
    "\t\tmodifiers= Shift+Control+Alt+LevelThree;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[Control]= 1;\n"
    "\t\tpreserve[Control]= Control;\n"
    "\t\tmap[Shift+Control]= 2;\n"
    "\t\tpreserve[Shift+Control]= Control;\n"
    "\t\tmap[Control+LevelThree]= 3;\n"
    "\t\tpreserve[Control+LevelThree]= Control;\n"
    "\t\tmap[Shift+Control+LevelThree]= 4;\n"
    "\t\tpreserve[Shift+Control+LevelThree]= Control;\n"
    "\t\tmap[Alt]= 1;\n"
    "\t\tpreserve[Alt]= Alt;\n"
    "\t\tmap[Shift+Alt]= 2;\n"
    "\t\tpreserve[Shift+Alt]= Alt;\n"
    "\t\tmap[Alt+LevelThree]= 3;\n"
    "\t\tpreserve[Alt+LevelThree]= Alt;\n"
    "\t\tmap[Shift+Alt+LevelThree]= 4;\n"
    "\t\tpreserve[Shift+Alt+LevelThree]= Alt;\n"
    "\t\tmap[Control+Alt]= 5;\n"
    "\t\tmap[Shift+Control+Alt]= 2;\n"
    "\t\tpreserve[Shift+Control+Alt]= Control+Alt;\n"
    "\t\tmap[Control+Alt+LevelThree]= 3;\n"
    "\t\tpreserve[Control+Alt+LevelThree]= Control+Alt;\n"
    "\t\tmap[Shift+Control+Alt+LevelThree]= 4;\n"
    "\t\tpreserve[Shift+Control+Alt+LevelThree]= Control+Alt;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t\tlevel_name[5]= \"Ctrl+Alt\";\n"
    "\t};\n"
    "\ttype \"THREE_LEVEL\" {\n"
    "\t\tmodifiers= Shift+LevelThree;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 3;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"Level3\";\n"
    "\t};\n"
    "\ttype \"FOUR_LEVEL\" {\n"
    "\t\tmodifiers= Shift+LevelThree;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"FOUR_LEVEL_ALPHABETIC\" {\n"
    "\t\tmodifiers= Shift+Lock+LevelThree;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[Lock]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[Lock+LevelThree]= 4;\n"
    "\t\tmap[Shift+Lock+LevelThree]= 3;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"FOUR_LEVEL_SEMIALPHABETIC\" {\n"
    "\t\tmodifiers= Shift+Lock+LevelThree;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[Lock]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[Lock+LevelThree]= 3;\n"
    "\t\tpreserve[Lock+LevelThree]= Lock;\n"
    "\t\tmap[Shift+Lock+LevelThree]= 4;\n"
    "\t\tpreserve[Shift+Lock+LevelThree]= Lock;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"FOUR_LEVEL_KEYPAD\" {\n"
    "\t\tmodifiers= Shift+NumLock+LevelThree;\n"
    "\t\tmap[Shift]= 1;\n"
    "\t\tpreserve[Shift]= Shift;\n"
    "\t\tmap[NumLock]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+NumLock]= 2;\n"
    "\t\tpreserve[Shift+NumLock]= Shift;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[NumLock+LevelThree]= 3;\n"
    "\t\tmap[Shift+NumLock+LevelThree]= 4;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"NumLock\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"FOUR_LEVEL_MIXED_KEYPAD\" {\n"
    "\t\tmodifiers= Shift+NumLock+LevelThree;\n"
    "\t\tmap[Shift]= 1;\n"
    "\t\tpreserve[Shift]= Shift;\n"
    "\t\tmap[NumLock]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+NumLock]= 2;\n"
    "\t\tpreserve[Shift+NumLock]= Shift;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[NumLock+LevelThree]= 3;\n"
    "\t\tmap[Shift+NumLock+LevelThree]= 4;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"NumLock\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"FOUR_LEVEL_LOCKABLE_LEVEL2\" {\n"
    "\t\tmodifiers= Shift+LevelThree+LevelFive;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[LevelFive]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[LevelThree+LevelFive]= 3;\n"
    "\t\tmap[Shift+LevelThree+LevelFive]= 4;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Digit\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"FOUR_LEVEL_X\" {\n"
    "\t\tmodifiers= Shift+Control+Alt+LevelThree;\n"
    "\t\tmap[Shift]= 1;\n"
    "\t\tpreserve[Shift]= Shift;\n"
    "\t\tmap[LevelThree]= 2;\n"
    "\t\tmap[Control]= 1;\n"
    "\t\tpreserve[Control]= Control;\n"
    "\t\tmap[Alt]= 1;\n"
    "\t\tpreserve[Alt]= Alt;\n"
    "\t\tmap[Shift+LevelThree]= 3;\n"
    "\t\tmap[Shift+Control]= 1;\n"
    "\t\tpreserve[Shift+Control]= Shift+Control;\n"
    "\t\tmap[Shift+Alt]= 1;\n"
    "\t\tpreserve[Shift+Alt]= Shift+Alt;\n"
    "\t\tmap[Control+LevelThree]= 2;\n"
    "\t\tpreserve[Control+LevelThree]= Control;\n"
    "\t\tmap[Alt+LevelThree]= 2;\n"
    "\t\tpreserve[Alt+LevelThree]= Alt;\n"
    "\t\tmap[Control+Alt]= 4;\n"
    "\t\tmap[Shift+Control+LevelThree]= 3;\n"
    "\t\tpreserve[Shift+Control+LevelThree]= Control;\n"
    "\t\tmap[Shift+Alt+LevelThree]= 3;\n"
    "\t\tpreserve[Shift+Alt+LevelThree]= Alt;\n"
    "\t\tmap[Shift+Control+Alt]= 4;\n"
    "\t\tpreserve[Shift+Control+Alt]= Shift;\n"
    "\t\tmap[Control+Alt+LevelThree]= 2;\n"
    "\t\tpreserve[Control+Alt+LevelThree]= Control+Alt;\n"
    "\t\tmap[Shift+Control+Alt+LevelThree]= 3;\n"
    "\t\tpreserve[Shift+Control+Alt+LevelThree]= Control+Alt;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"AltGr\";\n"
    "\t\tlevel_name[3]= \"Shift AltGr\";\n"
    "\t\tlevel_name[4]= \"Ctrl+Alt\";\n"
    "\t};\n"
    "\ttype \"SEPARATE_CAPS_AND_SHIFT_ALPHABETIC\" {\n"
    "\t\tmodifiers= Shift+Lock+LevelThree;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[Lock]= 4;\n"
    "\t\tpreserve[Lock]= Lock;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[Lock+LevelThree]= 3;\n"
    "\t\tpreserve[Lock+LevelThree]= Lock;\n"
    "\t\tmap[Shift+Lock+LevelThree]= 3;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Caps / Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"FOUR_LEVEL_PLUS_LOCK\" {\n"
    "\t\tmodifiers= Shift+Lock+LevelThree;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[Lock]= 5;\n"
    "\t\tmap[Shift+Lock]= 2;\n"
    "\t\tmap[Lock+LevelThree]= 3;\n"
    "\t\tmap[Shift+Lock+LevelThree]= 4;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t\tlevel_name[5]= \"Lock\";\n"
    "\t};\n"
    "\ttype \"EIGHT_LEVEL\" {\n"
    "\t\tmodifiers= Shift+LevelThree+LevelFive;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[LevelFive]= 5;\n"
    "\t\tmap[Shift+LevelFive]= 6;\n"
    "\t\tmap[LevelThree+LevelFive]= 7;\n"
    "\t\tmap[Shift+LevelThree+LevelFive]= 8;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t\tlevel_name[5]= \"X\";\n"
    "\t\tlevel_name[6]= \"X Shift\";\n"
    "\t\tlevel_name[7]= \"X AltGr\";\n"
    "\t\tlevel_name[8]= \"X Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"EIGHT_LEVEL_ALPHABETIC\" {\n"
    "\t\tmodifiers= Shift+Lock+LevelThree+LevelFive;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[Lock]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[Lock+LevelThree]= 4;\n"
    "\t\tmap[Shift+Lock+LevelThree]= 3;\n"
    "\t\tmap[LevelFive]= 5;\n"
    "\t\tmap[Shift+LevelFive]= 6;\n"
    "\t\tmap[Lock+LevelFive]= 6;\n"
    "\t\tmap[Shift+Lock+LevelFive]= 5;\n"
    "\t\tmap[LevelThree+LevelFive]= 7;\n"
    "\t\tmap[Shift+LevelThree+LevelFive]= 8;\n"
    "\t\tmap[Lock+LevelThree+LevelFive]= 8;\n"
    "\t\tmap[Shift+Lock+LevelThree+LevelFive]= 7;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t\tlevel_name[5]= \"X\";\n"
    "\t\tlevel_name[6]= \"X Shift\";\n"
    "\t\tlevel_name[7]= \"X AltGr\";\n"
    "\t\tlevel_name[8]= \"X Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"EIGHT_LEVEL_SEMIALPHABETIC\" {\n"
    "\t\tmodifiers= Shift+Lock+LevelThree+LevelFive;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[Lock]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[Lock+LevelThree]= 3;\n"
    "\t\tpreserve[Lock+LevelThree]= Lock;\n"
    "\t\tmap[Shift+Lock+LevelThree]= 4;\n"
    "\t\tpreserve[Shift+Lock+LevelThree]= Lock;\n"
    "\t\tmap[LevelFive]= 5;\n"
    "\t\tmap[Shift+LevelFive]= 6;\n"
    "\t\tmap[Lock+LevelFive]= 6;\n"
    "\t\tmap[Shift+Lock+LevelFive]= 5;\n"
    "\t\tmap[LevelThree+LevelFive]= 7;\n"
    "\t\tmap[Shift+LevelThree+LevelFive]= 8;\n"
    "\t\tmap[Lock+LevelThree+LevelFive]= 7;\n"
    "\t\tpreserve[Lock+LevelThree+LevelFive]= Lock;\n"
    "\t\tmap[Shift+Lock+LevelThree+LevelFive]= 8;\n"
    "\t\tpreserve[Shift+Lock+LevelThree+LevelFive]= Lock;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t\tlevel_name[5]= \"X\";\n"
    "\t\tlevel_name[6]= \"X Shift\";\n"
    "\t\tlevel_name[7]= \"X AltGr\";\n"
    "\t\tlevel_name[8]= \"X Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"EIGHT_LEVEL_WITH_LEVEL5_LOCK\" {\n"
    "\t\tmodifiers= Shift+NumLock+LevelThree+LevelFive;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[LevelFive]= 5;\n"
    "\t\tmap[Shift+LevelFive]= 6;\n"
    "\t\tpreserve[Shift+LevelFive]= Shift;\n"
    "\t\tmap[LevelThree+LevelFive]= 7;\n"
    "\t\tmap[Shift+LevelThree+LevelFive]= 8;\n"
    "\t\tmap[NumLock]= 5;\n"
    "\t\tmap[Shift+NumLock]= 6;\n"
    "\t\tpreserve[Shift+NumLock]= Shift;\n"
    "\t\tmap[NumLock+LevelThree]= 7;\n"
    "\t\tmap[Shift+NumLock+LevelThree]= 8;\n"
    "\t\tmap[Shift+NumLock+LevelFive]= 2;\n"
    "\t\tmap[NumLock+LevelThree+LevelFive]= 3;\n"
    "\t\tmap[Shift+NumLock+LevelThree+LevelFive]= 4;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t\tlevel_name[5]= \"X\";\n"
    "\t\tlevel_name[6]= \"X Shift\";\n"
    "\t\tlevel_name[7]= \"X AltGr\";\n"
    "\t\tlevel_name[8]= \"X Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"EIGHT_LEVEL_ALPHABETIC_WITH_LEVEL5_LOCK\" {\n"
    "\t\tmodifiers= Shift+Lock+NumLock+LevelThree+LevelFive;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[LevelFive]= 5;\n"
    "\t\tmap[Shift+LevelFive]= 6;\n"
    "\t\tpreserve[Shift+LevelFive]= Shift;\n"
    "\t\tmap[LevelThree+LevelFive]= 7;\n"
    "\t\tmap[Shift+LevelThree+LevelFive]= 8;\n"
    "\t\tmap[NumLock]= 5;\n"
    "\t\tmap[Shift+NumLock]= 6;\n"
    "\t\tpreserve[Shift+NumLock]= Shift;\n"
    "\t\tmap[NumLock+LevelThree]= 7;\n"
    "\t\tmap[Shift+NumLock+LevelThree]= 8;\n"
    "\t\tmap[Shift+NumLock+LevelFive]= 2;\n"
    "\t\tmap[NumLock+LevelThree+LevelFive]= 3;\n"
    "\t\tmap[Shift+NumLock+LevelThree+LevelFive]= 4;\n"
    "\t\tmap[Lock]= 2;\n"
    "\t\tmap[Lock+LevelThree]= 3;\n"
    "\t\tmap[Shift+Lock+LevelThree]= 4;\n"
    "\t\tmap[Lock+LevelFive]= 5;\n"
    "\t\tmap[Shift+Lock+LevelFive]= 6;\n"
    "\t\tmap[Lock+LevelThree+LevelFive]= 7;\n"
    "\t\tmap[Shift+Lock+LevelThree+LevelFive]= 8;\n"
    "\t\tmap[Lock+NumLock]= 5;\n"
    "\t\tmap[Shift+Lock+NumLock]= 6;\n"
    "\t\tmap[Lock+NumLock+LevelThree]= 7;\n"
    "\t\tmap[Shift+Lock+NumLock+LevelThree]= 8;\n"
    "\t\tmap[Lock+NumLock+LevelFive]= 2;\n"
    "\t\tmap[Lock+NumLock+LevelThree+LevelFive]= 3;\n"
    "\t\tmap[Shift+Lock+NumLock+LevelThree+LevelFive]= 4;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"AltGr\";\n"
    "\t\tlevel_name[4]= \"Shift AltGr\";\n"
    "\t\tlevel_name[5]= \"X\";\n"
    "\t\tlevel_name[6]= \"X Shift\";\n"
    "\t\tlevel_name[7]= \"X AltGr\";\n"
    "\t\tlevel_name[8]= \"X Shift AltGr\";\n"
    "\t};\n"
    "\ttype \"EIGHT_LEVEL_BY_CTRL\" {\n"
    "\t\tmodifiers= Shift+Lock+Control+LevelThree;\n"
    "\t\tmap[Shift]= 2;\n"
    "\t\tmap[Lock]= 2;\n"
    "\t\tmap[LevelThree]= 3;\n"
    "\t\tmap[Shift+LevelThree]= 4;\n"
    "\t\tmap[Lock+LevelThree]= 4;\n"
    "\t\tmap[Shift+Lock+LevelThree]= 3;\n"
    "\t\tmap[Control]= 5;\n"
    "\t\tmap[Shift+Control]= 6;\n"
    "\t\tmap[Lock+Control]= 6;\n"
    "\t\tmap[Shift+Lock+Control]= 5;\n"
    "\t\tmap[Control+LevelThree]= 7;\n"
    "\t\tmap[Shift+Control+LevelThree]= 8;\n"
    "\t\tmap[Lock+Control+LevelThree]= 8;\n"
    "\t\tmap[Shift+Lock+Control+LevelThree]= 7;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift\";\n"
    "\t\tlevel_name[3]= \"Level3\";\n"
    "\t\tlevel_name[4]= \"Shift Level3\";\n"
    "\t\tlevel_name[5]= \"Ctrl\";\n"
    "\t\tlevel_name[6]= \"Shift Ctrl\";\n"
    "\t\tlevel_name[7]= \"Level3 Ctrl\";\n"
    "\t\tlevel_name[8]= \"Shift Level3 Ctrl\";\n"
    "\t};\n"
    "\ttype \"KEYPAD\" {\n"
    "\t\tmodifiers= NumLock;\n"
    "\t\tmap[NumLock]= 2;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Number\";\n"
    "\t};\n"
    "\ttype \"SHIFT+ALT\" {\n"
    "\t\tmodifiers= Shift+Alt;\n"
    "\t\tmap[Shift+Alt]= 2;\n"
    "\t\tlevel_name[1]= \"Base\";\n"
    "\t\tlevel_name[2]= \"Shift+Alt\";\n"
    "\t};\n"
    "};\n"
    "\n"
    "xkb_compatibility \"complete\" {\n"
    "\tvirtual_modifiers NumLock,Alt,LevelThree,Super,LevelFive,Meta,Hyper=0x4000,ScrollLock=0x8000;\n"
    "\n"
    "\tinterpret.useModMapMods= AnyLevel;\n"
    "\tinterpret.repeat= False;\n"
    "\tinterpret ISO_Level2_Latch+Exactly(Shift) {\n"
    "\t\tuseModMapMods=level1;\n"
    "\t\taction= LatchMods(modifiers=Shift,clearLocks,latchToLock);\n"
    "\t};\n"
    "\tinterpret Shift_Lock+AnyOf(Shift+Lock) {\n"
    "\t\taction= LockMods(modifiers=Shift);\n"
    "\t};\n"
    "\tinterpret Num_Lock+AnyOf(all) {\n"
    "\t\tvirtualModifier= NumLock;\n"
    "\t\taction= LockMods(modifiers=NumLock);\n"
    "\t};\n"
    "\tinterpret ISO_Level3_Shift+AnyOf(all) {\n"
    "\t\tvirtualModifier= LevelThree;\n"
    "\t\tuseModMapMods=level1;\n"
    "\t\taction= SetMods(modifiers=LevelThree,clearLocks);\n"
    "\t};\n"
    "\tinterpret ISO_Level3_Latch+AnyOf(all) {\n"
    "\t\tvirtualModifier= LevelThree;\n"
    "\t\tuseModMapMods=level1;\n"
    "\t\taction= LatchMods(modifiers=LevelThree,clearLocks,latchToLock);\n"
    "\t};\n"
    "\tinterpret ISO_Level3_Lock+AnyOf(all) {\n"
    "\t\tvirtualModifier= LevelThree;\n"
    "\t\tuseModMapMods=level1;\n"
    "\t\taction= LockMods(modifiers=LevelThree);\n"
    "\t};\n"
    "\tinterpret Alt_L+AnyOf(all) {\n"
    "\t\tvirtualModifier= Alt;\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tinterpret Alt_R+AnyOf(all) {\n"
    "\t\tvirtualModifier= Alt;\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tinterpret Meta_L+AnyOf(all) {\n"
    "\t\tvirtualModifier= Meta;\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tinterpret Meta_R+AnyOf(all) {\n"
    "\t\tvirtualModifier= Meta;\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tinterpret Super_L+AnyOf(all) {\n"
    "\t\tvirtualModifier= Super;\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tinterpret Super_R+AnyOf(all) {\n"
    "\t\tvirtualModifier= Super;\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tinterpret Hyper_L+AnyOf(all) {\n"
    "\t\tvirtualModifier= Hyper;\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tinterpret Hyper_R+AnyOf(all) {\n"
    "\t\tvirtualModifier= Hyper;\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tinterpret Scroll_Lock+AnyOf(all) {\n"
    "\t\tvirtualModifier= ScrollLock;\n"
    "\t\taction= LockMods(modifiers=modMapMods);\n"
    "\t};\n"
    "\tinterpret ISO_Level5_Shift+AnyOf(all) {\n"
    "\t\tvirtualModifier= LevelFive;\n"
    "\t\tuseModMapMods=level1;\n"
    "\t\taction= SetMods(modifiers=LevelFive,clearLocks);\n"
    "\t};\n"
    "\tinterpret ISO_Level5_Latch+AnyOf(all) {\n"
    "\t\tvirtualModifier= LevelFive;\n"
    "\t\tuseModMapMods=level1;\n"
    "\t\taction= LatchMods(modifiers=LevelFive,clearLocks,latchToLock);\n"
    "\t};\n"
    "\tinterpret ISO_Level5_Lock+AnyOf(all) {\n"
    "\t\tvirtualModifier= LevelFive;\n"
    "\t\tuseModMapMods=level1;\n"
    "\t\taction= LockMods(modifiers=LevelFive);\n"
    "\t};\n"
    "\tinterpret ISO_Group_Shift+AnyOfOrNone(all) {\n"
    "\t\taction= SetGroup(group=+1);\n"
    "\t};\n"
    "\tinterpret ISO_Level3_Shift+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=LevelThree,clearLocks);\n"
    "\t};\n"
    "\tinterpret ISO_Level3_Latch+AnyOfOrNone(all) {\n"
    "\t\taction= LatchMods(modifiers=LevelThree,clearLocks,latchToLock);\n"
    "\t};\n"
    "\tinterpret ISO_Level3_Lock+AnyOfOrNone(all) {\n"
    "\t\taction= LockMods(modifiers=LevelThree);\n"
    "\t};\n"
    "\tinterpret ISO_Group_Latch+AnyOfOrNone(all) {\n"
    "\t\taction= LatchGroup(group=2);\n"
    "\t};\n"
    "\tinterpret ISO_Next_Group+AnyOfOrNone(all) {\n"
    "\t\taction= LockGroup(group=+1);\n"
    "\t};\n"
    "\tinterpret ISO_Prev_Group+AnyOfOrNone(all) {\n"
    "\t\taction= LockGroup(group=-1);\n"
    "\t};\n"
    "\tinterpret ISO_First_Group+AnyOfOrNone(all) {\n"
    "\t\taction= LockGroup(group=1);\n"
    "\t};\n"
    "\tinterpret ISO_Last_Group+AnyOfOrNone(all) {\n"
    "\t\taction= LockGroup(group=2);\n"
    "\t};\n"
    "\tinterpret KP_1+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=-1,y=+1);\n"
    "\t};\n"
    "\tinterpret KP_End+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=-1,y=+1);\n"
    "\t};\n"
    "\tinterpret KP_2+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+0,y=+1);\n"
    "\t};\n"
    "\tinterpret KP_Down+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+0,y=+1);\n"
    "\t};\n"
    "\tinterpret KP_3+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+1,y=+1);\n"
    "\t};\n"
    "\tinterpret KP_Next+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+1,y=+1);\n"
    "\t};\n"
    "\tinterpret KP_4+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=-1,y=+0);\n"
    "\t};\n"
    "\tinterpret KP_Left+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=-1,y=+0);\n"
    "\t};\n"
    "\tinterpret KP_6+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+1,y=+0);\n"
    "\t};\n"
    "\tinterpret KP_Right+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+1,y=+0);\n"
    "\t};\n"
    "\tinterpret KP_7+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=-1,y=-1);\n"
    "\t};\n"
    "\tinterpret KP_Home+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=-1,y=-1);\n"
    "\t};\n"
    "\tinterpret KP_8+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+0,y=-1);\n"
    "\t};\n"
    "\tinterpret KP_Up+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+0,y=-1);\n"
    "\t};\n"
    "\tinterpret KP_9+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+1,y=-1);\n"
    "\t};\n"
    "\tinterpret KP_Prior+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+1,y=-1);\n"
    "\t};\n"
    "\tinterpret KP_5+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= PtrBtn(button=default);\n"
    "\t};\n"
    "\tinterpret KP_Begin+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= PtrBtn(button=default);\n"
    "\t};\n"
    "\tinterpret KP_F2+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SetPtrDflt(affect=button,button=1);\n"
    "\t};\n"
    "\tinterpret KP_Divide+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SetPtrDflt(affect=button,button=1);\n"
    "\t};\n"
    "\tinterpret KP_F3+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SetPtrDflt(affect=button,button=2);\n"
    "\t};\n"
    "\tinterpret KP_Multiply+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SetPtrDflt(affect=button,button=2);\n"
    "\t};\n"
    "\tinterpret KP_F4+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SetPtrDflt(affect=button,button=3);\n"
    "\t};\n"
    "\tinterpret KP_Subtract+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SetPtrDflt(affect=button,button=3);\n"
    "\t};\n"
    "\tinterpret KP_Separator+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= PtrBtn(button=default,count=2);\n"
    "\t};\n"
    "\tinterpret KP_Add+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= PtrBtn(button=default,count=2);\n"
    "\t};\n"
    "\tinterpret KP_0+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= LockPtrBtn(button=default,affect=lock);\n"
    "\t};\n"
    "\tinterpret KP_Insert+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= LockPtrBtn(button=default,affect=lock);\n"
    "\t};\n"
    "\tinterpret KP_Decimal+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= LockPtrBtn(button=default,affect=unlock);\n"
    "\t};\n"
    "\tinterpret KP_Delete+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= LockPtrBtn(button=default,affect=unlock);\n"
    "\t};\n"
    "\tinterpret F25+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SetPtrDflt(affect=button,button=1);\n"
    "\t};\n"
    "\tinterpret F26+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SetPtrDflt(affect=button,button=2);\n"
    "\t};\n"
    "\tinterpret F27+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=-1,y=-1);\n"
    "\t};\n"
    "\tinterpret F29+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+1,y=-1);\n"
    "\t};\n"
    "\tinterpret F31+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= PtrBtn(button=default);\n"
    "\t};\n"
    "\tinterpret F33+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=-1,y=+1);\n"
    "\t};\n"
    "\tinterpret F35+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= MovePtr(x=+1,y=+1);\n"
    "\t};\n"
    "\tinterpret Pointer_Button_Dflt+AnyOfOrNone(all) {\n"
    "\t\taction= PtrBtn(button=default);\n"
    "\t};\n"
    "\tinterpret Pointer_Button1+AnyOfOrNone(all) {\n"
    "\t\taction= PtrBtn(button=1);\n"
    "\t};\n"
    "\tinterpret Pointer_Button2+AnyOfOrNone(all) {\n"
    "\t\taction= PtrBtn(button=2);\n"
    "\t};\n"
    "\tinterpret Pointer_Button3+AnyOfOrNone(all) {\n"
    "\t\taction= PtrBtn(button=3);\n"
    "\t};\n"
    "\tinterpret Pointer_DblClick_Dflt+AnyOfOrNone(all) {\n"
    "\t\taction= PtrBtn(button=default,count=2);\n"
    "\t};\n"
    "\tinterpret Pointer_DblClick1+AnyOfOrNone(all) {\n"
    "\t\taction= PtrBtn(button=1,count=2);\n"
    "\t};\n"
    "\tinterpret Pointer_DblClick2+AnyOfOrNone(all) {\n"
    "\t\taction= PtrBtn(button=2,count=2);\n"
    "\t};\n"
    "\tinterpret Pointer_DblClick3+AnyOfOrNone(all) {\n"
    "\t\taction= PtrBtn(button=3,count=2);\n"
    "\t};\n"
    "\tinterpret Pointer_Drag_Dflt+AnyOfOrNone(all) {\n"
    "\t\taction= LockPtrBtn(button=default,affect=both);\n"
    "\t};\n"
    "\tinterpret Pointer_Drag1+AnyOfOrNone(all) {\n"
    "\t\taction= LockPtrBtn(button=1,affect=both);\n"
    "\t};\n"
    "\tinterpret Pointer_Drag2+AnyOfOrNone(all) {\n"
    "\t\taction= LockPtrBtn(button=2,affect=both);\n"
    "\t};\n"
    "\tinterpret Pointer_Drag3+AnyOfOrNone(all) {\n"
    "\t\taction= LockPtrBtn(button=3,affect=both);\n"
    "\t};\n"
    "\tinterpret Pointer_EnableKeys+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=MouseKeys);\n"
    "\t};\n"
    "\tinterpret Pointer_Accelerate+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=MouseKeysAccel);\n"
    "\t};\n"
    "\tinterpret Pointer_DfltBtnNext+AnyOfOrNone(all) {\n"
    "\t\taction= SetPtrDflt(affect=button,button=+1);\n"
    "\t};\n"
    "\tinterpret Pointer_DfltBtnPrev+AnyOfOrNone(all) {\n"
    "\t\taction= SetPtrDflt(affect=button,button=-1);\n"
    "\t};\n"
    "\tinterpret AccessX_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=AccessXKeys);\n"
    "\t};\n"
    "\tinterpret AccessX_Feedback_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=AccessXFeedback);\n"
    "\t};\n"
    "\tinterpret RepeatKeys_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=RepeatKeys);\n"
    "\t};\n"
    "\tinterpret SlowKeys_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=SlowKeys);\n"
    "\t};\n"
    "\tinterpret BounceKeys_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=BounceKeys);\n"
    "\t};\n"
    "\tinterpret StickyKeys_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=StickyKeys);\n"
    "\t};\n"
    "\tinterpret MouseKeys_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=MouseKeys);\n"
    "\t};\n"
    "\tinterpret MouseKeys_Accel_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=MouseKeysAccel);\n"
    "\t};\n"
    "\tinterpret Overlay1_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=none);\n"
    "\t};\n"
    "\tinterpret Overlay2_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=none);\n"
    "\t};\n"
    "\tinterpret AudibleBell_Enable+AnyOfOrNone(all) {\n"
    "\t\taction= LockControls(controls=AudibleBell);\n"
    "\t};\n"
    "\tinterpret Terminate_Server+AnyOfOrNone(all) {\n"
    "\t\taction= Terminate();\n"
    "\t};\n"
    "\tinterpret Alt_L+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Alt,clearLocks);\n"
    "\t};\n"
    "\tinterpret Alt_R+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Alt,clearLocks);\n"
    "\t};\n"
    "\tinterpret Meta_L+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Meta,clearLocks);\n"
    "\t};\n"
    "\tinterpret Meta_R+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Meta,clearLocks);\n"
    "\t};\n"
    "\tinterpret Super_L+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Super,clearLocks);\n"
    "\t};\n"
    "\tinterpret Super_R+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Super,clearLocks);\n"
    "\t};\n"
    "\tinterpret Hyper_L+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Hyper,clearLocks);\n"
    "\t};\n"
    "\tinterpret Hyper_R+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Hyper,clearLocks);\n"
    "\t};\n"
    "\tinterpret Shift_L+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Shift,clearLocks);\n"
    "\t};\n"
    "\tinterpret Shift_R+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=Shift,clearLocks);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_1+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=1,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_2+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=2,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_3+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=3,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_4+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=4,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_5+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=5,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_6+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=6,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_7+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=7,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_8+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=8,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_9+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=9,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_10+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=10,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_11+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=11,!same);\n"
    "\t};\n"
    "\tinterpret XF86Switch_VT_12+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= SwitchScreen(screen=12,!same);\n"
    "\t};\n"
    "\tinterpret XF86LogGrabInfo+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= Private(type=0x86,data[0]=0x50,data[1]=0x72,data[2]=0x47,data[3]=0x72,data[4]=0x62,data[5]=0x73,data[6]=0x00);\n"
    "\t};\n"
    "\tinterpret XF86LogWindowTree+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= Private(type=0x86,data[0]=0x50,data[1]=0x72,data[2]=0x57,data[3]=0x69,data[4]=0x6e,data[5]=0x73,data[6]=0x00);\n"
    "\t};\n"
    "\tinterpret XF86Next_VMode+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= Private(type=0x86,data[0]=0x2b,data[1]=0x56,data[2]=0x4d,data[3]=0x6f,data[4]=0x64,data[5]=0x65,data[6]=0x00);\n"
    "\t};\n"
    "\tinterpret XF86Prev_VMode+AnyOfOrNone(all) {\n"
    "\t\trepeat= True;\n"
    "\t\taction= Private(type=0x86,data[0]=0x2d,data[1]=0x56,data[2]=0x4d,data[3]=0x6f,data[4]=0x64,data[5]=0x65,data[6]=0x00);\n"
    "\t};\n"
    "\tinterpret ISO_Level5_Shift+AnyOfOrNone(all) {\n"
    "\t\taction= SetMods(modifiers=LevelFive,clearLocks);\n"
    "\t};\n"
    "\tinterpret ISO_Level5_Latch+AnyOfOrNone(all) {\n"
    "\t\taction= LatchMods(modifiers=LevelFive,clearLocks,latchToLock);\n"
    "\t};\n"
    "\tinterpret ISO_Level5_Lock+AnyOfOrNone(all) {\n"
    "\t\taction= LockMods(modifiers=LevelFive);\n"
    "\t};\n"
    "\tinterpret Caps_Lock+AnyOfOrNone(all) {\n"
    "\t\taction= LockMods(modifiers=Lock);\n"
    "\t};\n"
    "\tinterpret Any+Exactly(Lock) {\n"
    "\t\taction= LockMods(modifiers=Lock);\n"
    "\t};\n"
    "\tinterpret Any+AnyOf(all) {\n"
    "\t\taction= SetMods(modifiers=modMapMods,clearLocks);\n"
    "\t};\n"
    "\tindicator \"Caps Lock\" {\n"
    "\t\twhichModState= locked;\n"
    "\t\tmodifiers= Lock;\n"
    "\t};\n"
    "\tindicator \"Num Lock\" {\n"
    "\t\twhichModState= locked;\n"
    "\t\tmodifiers= NumLock;\n"
    "\t};\n"
    "\tindicator \"Scroll Lock\" {\n"
    "\t\twhichModState= locked;\n"
    "\t\tmodifiers= ScrollLock;\n"
    "\t};\n"
    "\tindicator \"Shift Lock\" {\n"
    "\t\twhichModState= locked;\n"
    "\t\tmodifiers= Shift;\n"
    "\t};\n"
    "\tindicator \"Group 2\" {\n"
    "\t\tgroups= 0xfffffffe;\n"
    "\t};\n"
    "\tindicator \"Mouse Keys\" {\n"
    "\t\tcontrols= MouseKeys;\n"
    "\t};\n"
    "};\n"
    "\n"
    "xkb_symbols \"pc_us_inet(evdev)\" {\n"
    "\tname[1]=\"English (US)\";\n"
    "\n"
    "\tkey <ESC>                {\t[          Escape ] };\n"
    "\tkey <AE01>               {\t[               1,          exclam ] };\n"
    "\tkey <AE02>               {\t[               2,              at ] };\n"
    "\tkey <AE03>               {\t[               3,      numbersign ] };\n"
    "\tkey <AE04>               {\t[               4,          dollar ] };\n"
    "\tkey <AE05>               {\t[               5,         percent ] };\n"
    "\tkey <AE06>               {\t[               6,     asciicircum ] };\n"
    "\tkey <AE07>               {\t[               7,       ampersand ] };\n"
    "\tkey <AE08>               {\t[               8,        asterisk ] };\n"
    "\tkey <AE09>               {\t[               9,       parenleft ] };\n"
    "\tkey <AE10>               {\t[               0,      parenright ] };\n"
    "\tkey <AE11>               {\t[           minus,      underscore ] };\n"
    "\tkey <AE12>               {\t[           equal,            plus ] };\n"
    "\tkey <BKSP>               {\t[       BackSpace,       BackSpace ] };\n"
    "\tkey <TAB>                {\t[             Tab,    ISO_Left_Tab ] };\n"
    "\tkey <AD01>               {\t[               q,               Q ] };\n"
    "\tkey <AD02>               {\t[               w,               W ] };\n"
    "\tkey <AD03>               {\t[               e,               E ] };\n"
    "\tkey <AD04>               {\t[               r,               R ] };\n"
    "\tkey <AD05>               {\t[               t,               T ] };\n"
    "\tkey <AD06>               {\t[               y,               Y ] };\n"
    "\tkey <AD07>               {\t[               u,               U ] };\n"
    "\tkey <AD08>               {\t[               i,               I ] };\n"
    "\tkey <AD09>               {\t[               o,               O ] };\n"
    "\tkey <AD10>               {\t[               p,               P ] };\n"
    "\tkey <AD11>               {\t[     bracketleft,       braceleft ] };\n"
    "\tkey <AD12>               {\t[    bracketright,      braceright ] };\n"
    "\tkey <RTRN>               {\t[          Return ] };\n"
    "\tkey <LCTL>               {\t[       Control_L ] };\n"
    "\tkey <AC01>               {\t[               a,               A ] };\n"
    "\tkey <AC02>               {\t[               s,               S ] };\n"
    "\tkey <AC03>               {\t[               d,               D ] };\n"
    "\tkey <AC04>               {\t[               f,               F ] };\n"
    "\tkey <AC05>               {\t[               g,               G ] };\n"
    "\tkey <AC06>               {\t[               h,               H ] };\n"
    "\tkey <AC07>               {\t[               j,               J ] };\n"
    "\tkey <AC08>               {\t[               k,               K ] };\n"
    "\tkey <AC09>               {\t[               l,               L ] };\n"
    "\tkey <AC10>               {\t[       semicolon,           colon ] };\n"
    "\tkey <AC11>               {\t[      apostrophe,        quotedbl ] };\n"
    "\tkey <TLDE>               {\t[           grave,      asciitilde ] };\n"
    "\tkey <LFSH>               {\t[         Shift_L ] };\n"
    "\tkey <BKSL>               {\t[       backslash,             bar ] };\n"
    "\tkey <AB01>               {\t[               z,               Z ] };\n"
    "\tkey <AB02>               {\t[               x,               X ] };\n"
    "\tkey <AB03>               {\t[               c,               C ] };\n"
    "\tkey <AB04>               {\t[               v,               V ] };\n"
    "\tkey <AB05>               {\t[               b,               B ] };\n"
    "\tkey <AB06>               {\t[               n,               N ] };\n"
    "\tkey <AB07>               {\t[               m,               M ] };\n"
    "\tkey <AB08>               {\t[           comma,            less ] };\n"
    "\tkey <AB09>               {\t[          period,         greater ] };\n"
    "\tkey <AB10>               {\t[           slash,        question ] };\n"
    "\tkey <RTSH>               {\t[         Shift_R ] };\n"
    "\tkey <KPMU>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [     KP_Multiply,     KP_Multiply,     KP_Multiply,     KP_Multiply,   XF86ClearGrab ]\n"
    "\t};\n"
    "\tkey <LALT>               {\t[           Alt_L ] };\n"
    "\tkey <SPCE>               {\t[           space ] };\n"
    "\tkey <CAPS>               {\t[       Caps_Lock ] };\n"
    "\tkey <FK01>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F1,              F1,              F1,              F1, XF86Switch_VT_1 ]\n"
    "\t};\n"
    "\tkey <FK02>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F2,              F2,              F2,              F2, XF86Switch_VT_2 ]\n"
    "\t};\n"
    "\tkey <FK03>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F3,              F3,              F3,              F3, XF86Switch_VT_3 ]\n"
    "\t};\n"
    "\tkey <FK04>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F4,              F4,              F4,              F4, XF86Switch_VT_4 ]\n"
    "\t};\n"
    "\tkey <FK05>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F5,              F5,              F5,              F5, XF86Switch_VT_5 ]\n"
    "\t};\n"
    "\tkey <FK06>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F6,              F6,              F6,              F6, XF86Switch_VT_6 ]\n"
    "\t};\n"
    "\tkey <FK07>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F7,              F7,              F7,              F7, XF86Switch_VT_7 ]\n"
    "\t};\n"
    "\tkey <FK08>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F8,              F8,              F8,              F8, XF86Switch_VT_8 ]\n"
    "\t};\n"
    "\tkey <FK09>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [              F9,              F9,              F9,              F9, XF86Switch_VT_9 ]\n"
    "\t};\n"
    "\tkey <FK10>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [             F10,             F10,             F10,             F10, XF86Switch_VT_10 ]\n"
    "\t};\n"
    "\tkey <NMLK>               {\t[        Num_Lock ] };\n"
    "\tkey <SCLK>               {\t[     Scroll_Lock ] };\n"
    "\tkey <KP7>                {\t[         KP_Home,            KP_7 ] };\n"
    "\tkey <KP8>                {\t[           KP_Up,            KP_8 ] };\n"
    "\tkey <KP9>                {\t[        KP_Prior,            KP_9 ] };\n"
    "\tkey <KPSU>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [     KP_Subtract,     KP_Subtract,     KP_Subtract,     KP_Subtract,  XF86Prev_VMode ]\n"
    "\t};\n"
    "\tkey <KP4>                {\t[         KP_Left,            KP_4 ] };\n"
    "\tkey <KP5>                {\t[        KP_Begin,            KP_5 ] };\n"
    "\tkey <KP6>                {\t[        KP_Right,            KP_6 ] };\n"
    "\tkey <KPAD>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [          KP_Add,          KP_Add,          KP_Add,          KP_Add,  XF86Next_VMode ]\n"
    "\t};\n"
    "\tkey <KP1>                {\t[          KP_End,            KP_1 ] };\n"
    "\tkey <KP2>                {\t[         KP_Down,            KP_2 ] };\n"
    "\tkey <KP3>                {\t[         KP_Next,            KP_3 ] };\n"
    "\tkey <KP0>                {\t[       KP_Insert,            KP_0 ] };\n"
    "\tkey <KPDL>               {\t[       KP_Delete,      KP_Decimal ] };\n"
    "\tkey <LVL3>               {\t[ ISO_Level3_Shift ] };\n"
    "\tkey <ZEHA>               {\n"
    "\t\ttype= \"PC_CONTROL_SUPER_LEVEL2\",\n"
    "\t\tsymbols[1]= [             F24, XF86TouchpadToggle ]\n"
    "\t};\n"
    "\tkey <LSGT>               {\t[            less,         greater,             bar,       brokenbar ] };\n"
    "\tkey <FK11>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [             F11,             F11,             F11,             F11, XF86Switch_VT_11 ]\n"
    "\t};\n"
    "\tkey <FK12>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [             F12,             F12,             F12,             F12, XF86Switch_VT_12 ]\n"
    "\t};\n"
    "\tkey <KATA>               {\t[        Katakana ] };\n"
    "\tkey <HIRA>               {\t[        Hiragana ] };\n"
    "\tkey <HENK>               {\t[     Henkan_Mode ] };\n"
    "\tkey <HKTG>               {\t[ Hiragana_Katakana ] };\n"
    "\tkey <MUHE>               {\t[        Muhenkan ] };\n"
    "\tkey <KPEN>               {\t[        KP_Enter ] };\n"
    "\tkey <RCTL>               {\t[       Control_R ] };\n"
    "\tkey <KPDV>               {\n"
    "\t\ttype= \"CTRL+ALT\",\n"
    "\t\tsymbols[1]= [       KP_Divide,       KP_Divide,       KP_Divide,       KP_Divide,      XF86Ungrab ]\n"
    "\t};\n"
    "\tkey <PRSC>               {\n"
    "\t\ttype= \"PC_ALT_LEVEL2\",\n"
    "\t\tsymbols[1]= [           Print,         Sys_Req ]\n"
    "\t};\n"
    "\tkey <RALT>               {\t[           Alt_R ] };\n"
    "\tkey <LNFD>               {\t[        Linefeed ] };\n"
    "\tkey <HOME>               {\t[            Home ] };\n"
    "\tkey <UP>                 {\t[              Up ] };\n"
    "\tkey <PGUP>               {\t[           Prior ] };\n"
    "\tkey <LEFT>               {\t[            Left ] };\n"
    "\tkey <RGHT>               {\t[           Right ] };\n"
    "\tkey <END>                {\t[             End ] };\n"
    "\tkey <DOWN>               {\t[            Down ] };\n"
    "\tkey <PGDN>               {\t[            Next ] };\n"
    "\tkey <INS>                {\t[          Insert ] };\n"
    "\tkey <DELE>               {\t[          Delete ] };\n"
    "\tkey <MUTE>               {\t[   XF86AudioMute ] };\n"
    "\tkey <VOL->               {\t[ XF86AudioLowerVolume ] };\n"
    "\tkey <VOL+>               {\t[ XF86AudioRaiseVolume ] };\n"
    "\tkey <POWR>               {\t[    XF86PowerOff ] };\n"
    "\tkey <KPEQ>               {\t[        KP_Equal ] };\n"
    "\tkey <I126>               {\t[       plusminus ] };\n"
    "\tkey <PAUS>               {\n"
    "\t\ttype= \"PC_CONTROL_LEVEL2\",\n"
    "\t\tsymbols[1]= [           Pause,           Break ]\n"
    "\t};\n"
    "\tkey <I128>               {\t[     XF86LaunchA ] };\n"
    "\tkey <I129>               {\t[      KP_Decimal,      KP_Decimal ] };\n"
    "\tkey <HNGL>               {\t[          Hangul ] };\n"
    "\tkey <HJCV>               {\t[    Hangul_Hanja ] };\n"
    "\tkey <LWIN>               {\t[         Super_L ] };\n"
    "\tkey <RWIN>               {\t[         Super_R ] };\n"
    "\tkey <COMP>               {\t[            Menu ] };\n"
    "\tkey <STOP>               {\t[          Cancel ] };\n"
    "\tkey <AGAI>               {\t[            Redo ] };\n"
    "\tkey <PROP>               {\t[        SunProps ] };\n"
    "\tkey <UNDO>               {\t[            Undo ] };\n"
    "\tkey <FRNT>               {\t[        SunFront ] };\n"
    "\tkey <COPY>               {\t[        XF86Copy ] };\n"
    "\tkey <OPEN>               {\t[        XF86Open ] };\n"
    "\tkey <PAST>               {\t[       XF86Paste ] };\n"
    "\tkey <FIND>               {\t[            Find ] };\n"
    "\tkey <CUT>                {\t[         XF86Cut ] };\n"
    "\tkey <HELP>               {\t[            Help ] };\n"
    "\tkey <I147>               {\t[      XF86MenuKB ] };\n"
    "\tkey <I148>               {\t[  XF86Calculator ] };\n"
    "\tkey <I150>               {\t[       XF86Sleep ] };\n"
    "\tkey <I151>               {\t[      XF86WakeUp ] };\n"
    "\tkey <I152>               {\t[    XF86Explorer ] };\n"
    "\tkey <I153>               {\t[        XF86Send ] };\n"
    "\tkey <I155>               {\t[        XF86Xfer ] };\n"
    "\tkey <I156>               {\t[     XF86Launch1 ] };\n"
    "\tkey <I157>               {\t[     XF86Launch2 ] };\n"
    "\tkey <I158>               {\t[         XF86WWW ] };\n"
    "\tkey <I159>               {\t[         XF86DOS ] };\n"
    "\tkey <I160>               {\t[ XF86ScreenSaver ] };\n"
    "\tkey <I161>               {\t[ XF86RotateWindows ] };\n"
    "\tkey <I162>               {\t[    XF86TaskPane ] };\n"
    "\tkey <I163>               {\t[        XF86Mail ] };\n"
    "\tkey <I164>               {\t[   XF86Favorites ] };\n"
    "\tkey <I165>               {\t[  XF86MyComputer ] };\n"
    "\tkey <I166>               {\t[        XF86Back ] };\n"
    "\tkey <I167>               {\t[     XF86Forward ] };\n"
    "\tkey <I169>               {\t[       XF86Eject ] };\n"
    "\tkey <I170>               {\t[       XF86Eject ] };\n"
    "\tkey <I171>               {\t[   XF86AudioNext ] };\n"
    "\tkey <I172>               {\t[   XF86AudioPlay,  XF86AudioPause ] };\n"
    "\tkey <I173>               {\t[   XF86AudioPrev ] };\n"
    "\tkey <I174>               {\t[   XF86AudioStop,       XF86Eject ] };\n"
    "\tkey <I175>               {\t[ XF86AudioRecord ] };\n"
    "\tkey <I176>               {\t[ XF86AudioRewind ] };\n"
    "\tkey <I177>               {\t[       XF86Phone ] };\n"
    "\tkey <I179>               {\t[       XF86Tools ] };\n"
    "\tkey <I180>               {\t[    XF86HomePage ] };\n"
    "\tkey <I181>               {\t[      XF86Reload ] };\n"
    "\tkey <I182>               {\t[       XF86Close ] };\n"
    "\tkey <I185>               {\t[    XF86ScrollUp ] };\n"
    "\tkey <I186>               {\t[  XF86ScrollDown ] };\n"
    "\tkey <I187>               {\t[       parenleft ] };\n"
    "\tkey <I188>               {\t[      parenright ] };\n"
    "\tkey <I189>               {\t[         XF86New ] };\n"
    "\tkey <I190>               {\t[            Redo ] };\n"
    "\tkey <FK13>               {\t[       XF86Tools ] };\n"
    "\tkey <FK14>               {\t[     XF86Launch5 ] };\n"
    "\tkey <FK15>               {\t[     XF86Launch6 ] };\n"
    "\tkey <FK16>               {\t[     XF86Launch7 ] };\n"
    "\tkey <FK17>               {\t[     XF86Launch8 ] };\n"
    "\tkey <FK18>               {\t[     XF86Launch9 ] };\n"
    "\tkey <FK19>               {\t[             F19 ] };\n"
    "\tkey <FK20>               {\t[ XF86AudioMicMute ] };\n"
    "\tkey <FK21>               {\t[ XF86TouchpadToggle ] };\n"
    "\tkey <FK22>               {\t[  XF86TouchpadOn ] };\n"
    "\tkey <FK23>               {\n"
    "\t\ttype= \"PC_SHIFT_SUPER_LEVEL2\",\n"
    "\t\tsymbols[1]= [             F23,   XF86Assistant ]\n"
    "\t};\n"
    "\tkey <FK24>               {\n"
    "\t\ttype= \"PC_CONTROL_SUPER_LEVEL2\",\n"
    "\t\tsymbols[1]= [             F24, XF86TouchpadToggle ]\n"
    "\t};\n"
    "\tkey <LVL5>               {\t[ ISO_Level5_Shift ] };\n"
    "\tkey <ALT>                {\t[        NoSymbol,           Alt_L ] };\n"
    "\tkey <META>               {\t[        NoSymbol,          Meta_L ] };\n"
    "\tkey <SUPR>               {\t[        NoSymbol,         Super_L ] };\n"
    "\tkey <HYPR>               {\t[        NoSymbol,         Hyper_L ] };\n"
    "\tkey <I208>               {\t[   XF86AudioPlay ] };\n"
    "\tkey <I209>               {\t[  XF86AudioPause ] };\n"
    "\tkey <I210>               {\t[     XF86Launch3 ] };\n"
    "\tkey <I211>               {\t[     XF86Launch4 ] };\n"
    "\tkey <I212>               {\t[     XF86LaunchB ] };\n"
    "\tkey <I213>               {\t[     XF86Suspend ] };\n"
    "\tkey <I214>               {\t[       XF86Close ] };\n"
    "\tkey <I215>               {\t[   XF86AudioPlay ] };\n"
    "\tkey <I216>               {\t[ XF86AudioForward ] };\n"
    "\tkey <I217>               {\t[ XF86AudioBassBoost ] };\n"
    "\tkey <I218>               {\t[           Print ] };\n"
    "\tkey <I220>               {\t[      XF86WebCam ] };\n"
    "\tkey <I221>               {\t[ XF86AudioPreset ] };\n"
    "\tkey <I223>               {\t[        XF86Mail ] };\n"
    "\tkey <I224>               {\t[   XF86Messenger ] };\n"
    "\tkey <I225>               {\t[      XF86Search ] };\n"
    "\tkey <I226>               {\t[          XF86Go ] };\n"
    "\tkey <I227>               {\t[     XF86Finance ] };\n"
    "\tkey <I228>               {\t[        XF86Game ] };\n"
    "\tkey <I229>               {\t[        XF86Shop ] };\n"
    "\tkey <I231>               {\t[          Cancel ] };\n"
    "\tkey <I232>               {\t[ XF86MonBrightnessDown ] };\n"
    "\tkey <I233>               {\t[ XF86MonBrightnessUp ] };\n"
    "\tkey <I234>               {\t[  XF86AudioMedia ] };\n"
    "\tkey <I235>               {\t[     XF86Display ] };\n"
    "\tkey <I236>               {\t[ XF86KbdLightOnOff ] };\n"
    "\tkey <I237>               {\t[ XF86KbdBrightnessDown ] };\n"
    "\tkey <I238>               {\t[ XF86KbdBrightnessUp ] };\n"
    "\tkey <I239>               {\t[        XF86Send ] };\n"
    "\tkey <I240>               {\t[       XF86Reply ] };\n"
    "\tkey <I241>               {\t[ XF86MailForward ] };\n"
    "\tkey <I242>               {\t[        XF86Save ] };\n"
    "\tkey <I243>               {\t[   XF86Documents ] };\n"
    "\tkey <I244>               {\t[     XF86Battery ] };\n"
    "\tkey <I245>               {\t[   XF86Bluetooth ] };\n"
    "\tkey <I246>               {\t[        XF86WLAN ] };\n"
    "\tkey <I247>               {\t[         XF86UWB ] };\n"
    "\tkey <I249>               {\t[  XF86Next_VMode ] };\n"
    "\tkey <I250>               {\t[  XF86Prev_VMode ] };\n"
    "\tkey <I251>               {\t[ XF86MonBrightnessCycle ] };\n"
    "\tkey <I252>               {\t[ XF86BrightnessAuto ] };\n"
    "\tkey <I253>               {\t[  XF86DisplayOff ] };\n"
    "\tkey <I254>               {\t[        XF86WWAN ] };\n"
    "\tkey <I255>               {\t[      XF86RFKill ] };\n"
    "\tkey <I256>               {\t[ XF86AudioMicMute ] };\n"
    "\tkey <I360>               {\t[          XF86OK ] };\n"
    "\tkey <I361>               {\t[      XF86Select ] };\n"
    "\tkey <I362>               {\t[        XF86GoTo ] };\n"
    "\tkey <I363>               {\t[       XF86Clear ] };\n"
    "\tkey <I365>               {\t[      XF86Option ] };\n"
    "\tkey <I366>               {\t[        XF86Info ] };\n"
    "\tkey <I367>               {\t[        XF86Time ] };\n"
    "\tkey <I368>               {\t[  XF86VendorLogo ] };\n"
    "\tkey <I370>               {\t[ XF86MediaSelectProgramGuide ] };\n"
    "\tkey <I371>               {\t[ XF86NextFavorite ] };\n"
    "\tkey <I372>               {\t[   XF86Favorites ] };\n"
    "\tkey <I373>               {\t[ XF86MediaSelectProgramGuide ] };\n"
    "\tkey <I374>               {\t[ XF86MediaSelectHome ] };\n"
    "\tkey <I376>               {\t[ XF86MediaLanguageMenu ] };\n"
    "\tkey <I377>               {\t[ XF86MediaTitleMenu ] };\n"
    "\tkey <I378>               {\t[    XF86Subtitle ] };\n"
    "\tkey <I379>               {\t[  XF86CycleAngle ] };\n"
    "\tkey <I380>               {\t[  XF86FullScreen ] };\n"
    "\tkey <I381>               {\t[ XF86AudioChannelMode ] };\n"
    "\tkey <I382>               {\t[    XF86Keyboard ] };\n"
    "\tkey <I383>               {\t[ XF86AspectRatio ] };\n"
    "\tkey <I384>               {\t[ XF86MediaSelectPC ] };\n"
    "\tkey <I385>               {\t[ XF86MediaSelectTV ] };\n"
    "\tkey <I386>               {\t[ XF86MediaSelectCable ] };\n"
    "\tkey <I387>               {\t[ XF86MediaSelectVCR ] };\n"
    "\tkey <I388>               {\t[ XF86MediaSelectVCRPlus ] };\n"
    "\tkey <I389>               {\t[ XF86MediaSelectSatellite ] };\n"
    "\tkey <I391>               {\t[          XF86CD ] };\n"
    "\tkey <I392>               {\t[ XF86MediaSelectTape ] };\n"
    "\tkey <I393>               {\t[ XF86MediaSelectRadio ] };\n"
    "\tkey <I394>               {\t[ XF86MediaSelectTuner ] };\n"
    "\tkey <I395>               {\t[ XF86MediaPlayer ] };\n"
    "\tkey <I396>               {\t[ XF86MediaSelectTeletext ] };\n"
    "\tkey <I397>               {\t[         XF86DVD ] };\n"
    "\tkey <I398>               {\t[ XF86MediaSelectAuxiliary ] };\n"
    "\tkey <I400>               {\t[       XF86Audio ] };\n"
    "\tkey <I401>               {\t[       XF86Video ] };\n"
    "\tkey <I404>               {\t[        XF86Memo ] };\n"
    "\tkey <I405>               {\t[    XF86Calendar ] };\n"
    "\tkey <I406>               {\t[         XF86Red ] };\n"
    "\tkey <I407>               {\t[       XF86Green ] };\n"
    "\tkey <I408>               {\t[      XF86Yellow ] };\n"
    "\tkey <I409>               {\t[        XF86Blue ] };\n"
    "\tkey <I410>               {\t[   XF86ChannelUp ] };\n"
    "\tkey <I411>               {\t[ XF86ChannelDown ] };\n"
    "\tkey <I417>               {\t[ XF86MediaPlaySlow ] };\n"
    "\tkey <I418>               {\t[ XF86AudioRandomPlay ] };\n"
    "\tkey <I419>               {\t[       XF86Break ] };\n"
    "\tkey <I421>               {\t[ XF86NumberEntryMode ] };\n"
    "\tkey <I424>               {\t[  XF86VideoPhone ] };\n"
    "\tkey <I425>               {\t[        XF86Game ] };\n"
    "\tkey <I426>               {\t[      XF86ZoomIn ] };\n"
    "\tkey <I427>               {\t[     XF86ZoomOut ] };\n"
    "\tkey <I428>               {\t[   XF86ZoomReset ] };\n"
    "\tkey <I429>               {\t[        XF86Word ] };\n"
    "\tkey <I430>               {\t[      XF86Editor ] };\n"
    "\tkey <I431>               {\t[       XF86Excel ] };\n"
    "\tkey <I432>               {\t[ XF86GraphicsEditor ] };\n"
    "\tkey <I433>               {\t[ XF86Presentation ] };\n"
    "\tkey <I434>               {\t[    XF86Database ] };\n"
    "\tkey <I435>               {\t[        XF86News ] };\n"
    "\tkey <I436>               {\t[   XF86Voicemail ] };\n"
    "\tkey <I437>               {\t[ XF86Addressbook ] };\n"
    "\tkey <I438>               {\t[   XF86Messenger ] };\n"
    "\tkey <I439>               {\t[ XF86DisplayToggle ] };\n"
    "\tkey <I440>               {\t[  XF86SpellCheck ] };\n"
    "\tkey <I441>               {\t[      XF86LogOff ] };\n"
    "\tkey <I442>               {\t[          dollar ] };\n"
    "\tkey <I443>               {\t[        EuroSign ] };\n"
    "\tkey <I444>               {\t[   XF86FrameBack ] };\n"
    "\tkey <I445>               {\t[ XF86FrameForward ] };\n"
    "\tkey <I446>               {\t[ XF86ContextMenu ] };\n"
    "\tkey <I447>               {\t[ XF86MediaRepeat ] };\n"
    "\tkey <I448>               {\t[ XF8610ChannelsUp ] };\n"
    "\tkey <I449>               {\t[ XF8610ChannelsDown ] };\n"
    "\tkey <I450>               {\t[      XF86Images ] };\n"
    "\tkey <I452>               {\t[ XF86NotificationCenter ] };\n"
    "\tkey <I453>               {\t[ XF86PickupPhone ] };\n"
    "\tkey <I454>               {\t[ XF86HangupPhone ] };\n"
    "\tkey <I455>               {\t[   XF86LinkPhone ] };\n"
    "\tkey <I472>               {\t[          XF86Fn ] };\n"
    "\tkey <I473>               {\t[      XF86Fn_Esc ] };\n"
    "\tkey <I474>               {\t[       XF86Fn_F1 ] };\n"
    "\tkey <I475>               {\t[       XF86Fn_F2 ] };\n"
    "\tkey <I476>               {\t[       XF86Fn_F3 ] };\n"
    "\tkey <I477>               {\t[       XF86Fn_F4 ] };\n"
    "\tkey <I478>               {\t[       XF86Fn_F5 ] };\n"
    "\tkey <I479>               {\t[       XF86Fn_F6 ] };\n"
    "\tkey <I480>               {\t[       XF86Fn_F7 ] };\n"
    "\tkey <I481>               {\t[       XF86Fn_F8 ] };\n"
    "\tkey <I482>               {\t[       XF86Fn_F9 ] };\n"
    "\tkey <I483>               {\t[      XF86Fn_F10 ] };\n"
    "\tkey <I484>               {\t[      XF86Fn_F11 ] };\n"
    "\tkey <I485>               {\t[      XF86Fn_F12 ] };\n"
    "\tkey <I486>               {\t[        XF86Fn_1 ] };\n"
    "\tkey <I487>               {\t[        XF86Fn_2 ] };\n"
    "\tkey <I488>               {\t[        XF86Fn_D ] };\n"
    "\tkey <I489>               {\t[        XF86Fn_E ] };\n"
    "\tkey <I490>               {\t[        XF86Fn_F ] };\n"
    "\tkey <I491>               {\t[        XF86Fn_S ] };\n"
    "\tkey <I492>               {\t[        XF86Fn_B ] };\n"
    "\tkey <I493>               {\t[ XF86FnRightShift ] };\n"
    "\tkey <I505>               {\t[   braille_dot_1 ] };\n"
    "\tkey <I506>               {\t[   braille_dot_2 ] };\n"
    "\tkey <I507>               {\t[   braille_dot_3 ] };\n"
    "\tkey <I508>               {\t[   braille_dot_4 ] };\n"
    "\tkey <I509>               {\t[   braille_dot_5 ] };\n"
    "\tkey <I510>               {\t[   braille_dot_6 ] };\n"
    "\tkey <I511>               {\t[   braille_dot_7 ] };\n"
    "\tkey <I512>               {\t[   braille_dot_8 ] };\n"
    "\tkey <I513>               {\t[   braille_dot_9 ] };\n"
    "\tkey <I514>               {\t[   braille_dot_1 ] };\n"
    "\tkey <I520>               {\t[    XF86Numeric0 ] };\n"
    "\tkey <I521>               {\t[    XF86Numeric1 ] };\n"
    "\tkey <I522>               {\t[    XF86Numeric2 ] };\n"
    "\tkey <I523>               {\t[    XF86Numeric3 ] };\n"
    "\tkey <I524>               {\t[    XF86Numeric4 ] };\n"
    "\tkey <I525>               {\t[    XF86Numeric5 ] };\n"
    "\tkey <I526>               {\t[    XF86Numeric6 ] };\n"
    "\tkey <I527>               {\t[    XF86Numeric7 ] };\n"
    "\tkey <I528>               {\t[    XF86Numeric8 ] };\n"
    "\tkey <I529>               {\t[    XF86Numeric9 ] };\n"
    "\tkey <I530>               {\t[ XF86NumericStar ] };\n"
    "\tkey <I531>               {\t[ XF86NumericPound ] };\n"
    "\tkey <I532>               {\t[    XF86NumericA ] };\n"
    "\tkey <I533>               {\t[    XF86NumericB ] };\n"
    "\tkey <I534>               {\t[    XF86NumericC ] };\n"
    "\tkey <I535>               {\t[    XF86NumericD ] };\n"
    "\tkey <I536>               {\t[ XF86CameraFocus ] };\n"
    "\tkey <I537>               {\t[   XF86WPSButton ] };\n"
    "\tkey <I538>               {\t[ XF86TouchpadToggle ] };\n"
    "\tkey <I539>               {\t[  XF86TouchpadOn ] };\n"
    "\tkey <I540>               {\t[ XF86TouchpadOff ] };\n"
    "\tkey <I541>               {\t[ XF86CameraZoomIn ] };\n"
    "\tkey <I542>               {\t[ XF86CameraZoomOut ] };\n"
    "\tkey <I543>               {\t[    XF86CameraUp ] };\n"
    "\tkey <I544>               {\t[  XF86CameraDown ] };\n"
    "\tkey <I545>               {\t[  XF86CameraLeft ] };\n"
    "\tkey <I546>               {\t[ XF86CameraRight ] };\n"
    "\tkey <I547>               {\t[ XF86AttendantOn ] };\n"
    "\tkey <I548>               {\t[ XF86AttendantOff ] };\n"
    "\tkey <I549>               {\t[ XF86AttendantToggle ] };\n"
    "\tkey <I550>               {\t[ XF86LightsToggle ] };\n"
    "\tkey <I568>               {\t[   XF86ALSToggle ] };\n"
    "\tkey <I569>               {\t[ XF86RotationLockToggle ] };\n"
    "\tkey <I570>               {\t[ XF86RefreshRateToggle ] };\n"
    "\tkey <I584>               {\t[ XF86Buttonconfig ] };\n"
    "\tkey <I585>               {\t[ XF86Taskmanager ] };\n"
    "\tkey <I586>               {\t[     XF86Journal ] };\n"
    "\tkey <I587>               {\t[ XF86ControlPanel ] };\n"
    "\tkey <I588>               {\t[   XF86AppSelect ] };\n"
    "\tkey <I589>               {\t[ XF86Screensaver ] };\n"
    "\tkey <I590>               {\t[ XF86VoiceCommand ] };\n"
    "\tkey <I591>               {\t[   XF86Assistant ] };\n"
    "\tkey <I592>               {\t[  ISO_Next_Group ] };\n"
    "\tkey <I593>               {\t[ XF86EmojiPicker ] };\n"
    "\tkey <I594>               {\t[     XF86Dictate ] };\n"
    "\tkey <I595>               {\t[ XF86CameraAccessEnable ] };\n"
    "\tkey <I596>               {\t[ XF86CameraAccessDisable ] };\n"
    "\tkey <I597>               {\t[ XF86CameraAccessToggle ] };\n"
    "\tkey <I598>               {\t[ XF86Accessibility ] };\n"
    "\tkey <I599>               {\t[ XF86DoNotDisturb ] };\n"
    "\tkey <I600>               {\t[ XF86BrightnessMin ] };\n"
    "\tkey <I601>               {\t[ XF86BrightnessMax ] };\n"
    "\tkey <I602>               {\t[ XF86ElectronicPrivacyScreenOn ] };\n"
    "\tkey <I603>               {\t[ XF86ElectronicPrivacyScreenOff ] };\n"
    "\tkey <I604>               {\t[ XF86ActionOnSelection ] };\n"
    "\tkey <I605>               {\t[ XF86ContextualInsert ] };\n"
    "\tkey <I606>               {\t[ XF86ContextualQuery ] };\n"
    "\tkey <I616>               {\t[ XF86KbdInputAssistPrev ] };\n"
    "\tkey <I617>               {\t[ XF86KbdInputAssistNext ] };\n"
    "\tkey <I618>               {\t[ XF86KbdInputAssistPrevgroup ] };\n"
    "\tkey <I619>               {\t[ XF86KbdInputAssistNextgroup ] };\n"
    "\tkey <I620>               {\t[ XF86KbdInputAssistAccept ] };\n"
    "\tkey <I621>               {\t[ XF86KbdInputAssistCancel ] };\n"
    "\tkey <I622>               {\t[     XF86RightUp ] };\n"
    "\tkey <I623>               {\t[   XF86RightDown ] };\n"
    "\tkey <I624>               {\t[      XF86LeftUp ] };\n"
    "\tkey <I625>               {\t[    XF86LeftDown ] };\n"
    "\tkey <I626>               {\t[    XF86RootMenu ] };\n"
    "\tkey <I627>               {\t[ XF86MediaTopMenu ] };\n"
    "\tkey <I628>               {\t[   XF86Numeric11 ] };\n"
    "\tkey <I629>               {\t[   XF86Numeric12 ] };\n"
    "\tkey <I630>               {\t[   XF86AudioDesc ] };\n"
    "\tkey <I631>               {\t[      XF863DMode ] };\n"
    "\tkey <I632>               {\t[ XF86NextFavorite ] };\n"
    "\tkey <I633>               {\t[  XF86StopRecord ] };\n"
    "\tkey <I634>               {\t[ XF86PauseRecord ] };\n"
    "\tkey <I635>               {\t[         XF86VOD ] };\n"
    "\tkey <I636>               {\t[      XF86Unmute ] };\n"
    "\tkey <I637>               {\t[ XF86FastReverse ] };\n"
    "\tkey <I638>               {\t[ XF86SlowReverse ] };\n"
    "\tkey <I639>               {\t[        XF86Data ] };\n"
    "\tkey <I640>               {\t[ XF86OnScreenKeyboard ] };\n"
    "\tkey <I641>               {\t[ XF86PrivacyScreenToggle ] };\n"
    "\tkey <I642>               {\t[ XF86SelectiveScreenshot ] };\n"
    "\tkey <I643>               {\t[ XF86NextElement ] };\n"
    "\tkey <I644>               {\t[ XF86PreviousElement ] };\n"
    "\tkey <I645>               {\t[ XF86AutopilotEngageToggle ] };\n"
    "\tkey <I646>               {\t[ XF86MarkWaypoint ] };\n"
    "\tkey <I647>               {\t[         XF86Sos ] };\n"
    "\tkey <I648>               {\t[    XF86NavChart ] };\n"
    "\tkey <I649>               {\t[ XF86FishingChart ] };\n"
    "\tkey <I650>               {\t[ XF86SingleRangeRadar ] };\n"
    "\tkey <I651>               {\t[ XF86DualRangeRadar ] };\n"
    "\tkey <I652>               {\t[ XF86RadarOverlay ] };\n"
    "\tkey <I653>               {\t[ XF86TraditionalSonar ] };\n"
    "\tkey <I654>               {\t[ XF86ClearvuSonar ] };\n"
    "\tkey <I655>               {\t[ XF86SidevuSonar ] };\n"
    "\tkey <I656>               {\t[     XF86NavInfo ] };\n"
    "\tkey <I657>               {\t[ XF86BrightnessAdjust ] };\n"
    "\tkey <I664>               {\t[      XF86Macro1 ] };\n"
    "\tkey <I665>               {\t[      XF86Macro2 ] };\n"
    "\tkey <I666>               {\t[      XF86Macro3 ] };\n"
    "\tkey <I667>               {\t[      XF86Macro4 ] };\n"
    "\tkey <I668>               {\t[      XF86Macro5 ] };\n"
    "\tkey <I669>               {\t[      XF86Macro6 ] };\n"
    "\tkey <I670>               {\t[      XF86Macro7 ] };\n"
    "\tkey <I671>               {\t[      XF86Macro8 ] };\n"
    "\tkey <I672>               {\t[      XF86Macro9 ] };\n"
    "\tkey <I673>               {\t[     XF86Macro10 ] };\n"
    "\tkey <I674>               {\t[     XF86Macro11 ] };\n"
    "\tkey <I675>               {\t[     XF86Macro12 ] };\n"
    "\tkey <I676>               {\t[     XF86Macro13 ] };\n"
    "\tkey <I677>               {\t[     XF86Macro14 ] };\n"
    "\tkey <I678>               {\t[     XF86Macro15 ] };\n"
    "\tkey <I679>               {\t[     XF86Macro16 ] };\n"
    "\tkey <I680>               {\t[     XF86Macro17 ] };\n"
    "\tkey <I681>               {\t[     XF86Macro18 ] };\n"
    "\tkey <I682>               {\t[     XF86Macro19 ] };\n"
    "\tkey <I683>               {\t[     XF86Macro20 ] };\n"
    "\tkey <I684>               {\t[     XF86Macro21 ] };\n"
    "\tkey <I685>               {\t[     XF86Macro22 ] };\n"
    "\tkey <I686>               {\t[     XF86Macro23 ] };\n"
    "\tkey <I687>               {\t[     XF86Macro24 ] };\n"
    "\tkey <I688>               {\t[     XF86Macro25 ] };\n"
    "\tkey <I689>               {\t[     XF86Macro26 ] };\n"
    "\tkey <I690>               {\t[     XF86Macro27 ] };\n"
    "\tkey <I691>               {\t[     XF86Macro28 ] };\n"
    "\tkey <I692>               {\t[     XF86Macro29 ] };\n"
    "\tkey <I693>               {\t[     XF86Macro30 ] };\n"
    "\tkey <I696>               {\t[ XF86MacroRecordStart ] };\n"
    "\tkey <I697>               {\t[ XF86MacroRecordStop ] };\n"
    "\tkey <I698>               {\t[ XF86MacroPresetCycle ] };\n"
    "\tkey <I699>               {\t[ XF86MacroPreset1 ] };\n"
    "\tkey <I700>               {\t[ XF86MacroPreset2 ] };\n"
    "\tkey <I701>               {\t[ XF86MacroPreset3 ] };\n"
    "\tkey <I704>               {\t[ XF86KbdLcdMenu1 ] };\n"
    "\tkey <I705>               {\t[ XF86KbdLcdMenu2 ] };\n"
    "\tkey <I706>               {\t[ XF86KbdLcdMenu3 ] };\n"
    "\tkey <I707>               {\t[ XF86KbdLcdMenu4 ] };\n"
    "\tkey <I708>               {\t[ XF86KbdLcdMenu5 ] };\n"
    "\tkey <I709>               {\t[ XF86PerformanceMode ] };\n"
    "\tmodifier_map Shift { <LFSH>, <RTSH> };\n"
    "\tmodifier_map Lock { <CAPS> };\n"
    "\tmodifier_map Control { <LCTL>, <RCTL> };\n"
    "\tmodifier_map Mod1 { <LALT>, <RALT>, <ALT>, <META> };\n"
    "\tmodifier_map Mod2 { <NMLK> };\n"
    "\tmodifier_map Mod3 { <LVL5> };\n"
    "\tmodifier_map Mod4 { <LWIN>, <RWIN>, <SUPR> };\n"
    "\tmodifier_map Mod5 { <LVL3> };\n"
    "};\n"
    "\n"
    "};\n"
    "\n"
    ;
