#!/usr/bin/env bash
# Write CURRENT_PROJECT_VERSION for this build.
# Priority: WAWONA_BUILD_NUMBER > GITHUB_RUN_NUMBER > unix timestamp (local dev).
#
# Writes to $(SRCROOT)/.build/ so wwn-version.xcconfig can include it before
# Xcode resolves build settings (DERIVED_FILE_DIR include runs too late).
set -euo pipefail

bn="${WAWONA_BUILD_NUMBER:-${GITHUB_RUN_NUMBER:-$(date +%s)}}"

if [ -n "${SRCROOT:-}" ]; then
	out_dir="${SRCROOT}/.build"
	mkdir -p "$out_dir"
	out="${out_dir}/wwn-build-number.xcconfig"
else
	: "${DERIVED_FILE_DIR:?SRCROOT or DERIVED_FILE_DIR must be set}"
	out="${DERIVED_FILE_DIR}/wwn-build-number.xcconfig"
fi

cat > "$out" <<EOF
// Auto-generated by scripts/xcode-stamp-build-number.sh — do not edit.
CURRENT_PROJECT_VERSION = ${bn}
EOF

echo "WWN CURRENT_PROJECT_VERSION=${bn} (${out})" >&2
